### ISSUE TITLE
GER - National Focus Effects in the wrong areas

### ISSUE THREAD

**Issue by B5P0** [kalterkrieg/Kalterkrieg-bug-reports#106]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

none

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

Trial of Allegiance

### Explanation of the Issue

The focus Urban Revitiliazion talks about East Germany but the focus effects have nothing to do with it. Similarly the focus New Industrial Towns doesnt talk about east germany but the Focus effects it.

### Possible Cause

probably just a switch-up

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed, i how much i hate the German focus tree
