### ISSUE TITLE
The Deutsches Heer Event - minor typo

### ISSUE THREAD

**Issue by trooper828xx** [kalterkrieg/Kalterkrieg-bug-reports#11]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: spot optimization

**Explanation of the issue:**
Second paragraph, second sentence, second section publicly is misspelled as Publically 

**Screenshots:**
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/32004757/2d375932-9f30-454b-9c85-c7fdbf437561)

**Comment by Kennedy2523** [comment]
Fixed.
