### ISSUE TITLE
NEWS - Labor wins the 1951 Australasian elections

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#116]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Title should be capitalized and "the" shouldn't be in front of Labor. I understand it is filling in the winning party's name (the Conservatives for example) but it doesn't work for Labor.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/5ddf7014-81ff-40d8-bcca-f5eb207f9b76)

**Comment by Kennedy2523** [comment]
This is a scripted loc issue and needs a bit more work than just fixing a loc file.

**Comment by PLF444** [comment]
Fixed it by changing Labor's short version to Labor Party
