### ISSUE TITLE
ENG - Options swapped in event

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#119]
### Explanation of the Issue

![kmWS7kK](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/ca7a27d5-7c62-46c3-8dd9-0e703011855d)
These two options give the opposite effect that they should. 
event id is krg_eng.114

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
