### ISSUE TITLE
GER - Add a tooltip in some event telling you a bunch of buildings get destroyed to show war repairs

### ISSUE THREAD

**Issue by SuperGreenBeans** [kalterkrieg/Kalterkrieg-bug-reports#12]
<details>
<summary>Please Note (click to expand)</summary>
Suggestions that don't match this template will be closed. We understand this can seem harsh, but in order to ensure we are able to keep on track of bugs other serious issues it is vital our issue tracker is kept organised. The kinds of suggestions that will get close and directed elsewhere include, but are not limited to:
- Anything that suggests adding new content
- Anything that is focused around changing lore
- Anything that will take a significant amount of time to implement
- Anything that isn't specific and actionable change about existing content, as the template specifies
Please know that this isn't out of any disrespect for the ideas you might have for the mod, and encourage people with a passion to get involved either on the subreddit, the discord or even via joining the team itself. But that being said, suggestions that don't match this template will be closed.
</details>

**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1

**Describe the specific change you would like:**
I want some sort of clarity to tell the player that a bunch of buildings got destroyed and have to be repaired

**Explain the reasoning behind this actionable change:**
It is unclear this is the case at game start. I assumed that since nothing was there when I launched the game, there were no repairs to be done. Suddenly I noticed it and it came out of nowhere.

**Additional context or comments:**
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/107566822/c7317e19-1ccf-4d90-8987-7b26db480bc3)

**Comment by Axolotl3823** [comment]
@Texican-BC this should be added to on game start as it is for UK and Ireland
