### ISSUE TITLE
RUS,UKR - VP name change suggestions

### ISSUE THREAD

**Issue by TashMorgotov** [kalterkrieg/Kalterkrieg-bug-reports#121]
I suggest change some names to more correct toponyms:

- [x] Tbilisi to Tiflis

- [x] Ulan Ude to Verkhneudinsk
- [x] Kyzyl Orda to Perovsk
- [x] Alma-Ata to Verny
- [x] Bishkek to Pishpek
- [x] Syktyvkar to Ust-Sysolsk
- [x] Dnipropetrosk to Dnepr
- [x] Donetsk to Yuzovka
- [ ] Baranavicy to Baranovichy
- [x] Mahilou to Mogilev (and you have two Mogilevs. The correct one is that one which northern)
- [x] Viipuri to Vyborg
- [x] Kirkenes to Nikel (because Kirkenes is norwegian city, on russian territory Nikel)
- [x] Orsa to Orsha
- [x] Reval to Tallinn

Because these names were introduced by the Bolsheviks with their policy of nativization or contain indications of Bolshevik policy (red color in the names)

**Comment by MrCovenant000** [comment]
Fixed
