### ISSUE TITLE
New England Impossible to do "From Behind the Maple Line"

### ISSUE THREAD

**Issue by TeddyRooseveltFan12345678910** [kalterkrieg/Kalterkrieg-bug-reports#124]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

"Silent Hotfix"

### List any other mods used

Friendly Map, TWR GDP screen

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Everything except La Resistance

### Explanation of the Issue

The last focus of the New England military branch "From Behind the Maple Line" is impossible to do. 

### Steps to reproduce

Load up KRG and play as New England

### Possible Cause

You need to do a focus from the other sub-branch of the military branch, it is a prerequsite. However, both sub branches are mutually exclusive, so you cant do them. 

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/81603664/d367e316-c895-43e9-b945-7715d731aba2)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/81603664/4713b643-d9e3-48a6-a450-f8f44f1e89f0)

### Save File

[NEE_1956_01_18_08.zip](https://github.com/user-attachments/files/16112159/NEE_1956_01_18_08.zip)

### Log Files

[ai.log](https://github.com/user-attachments/files/16112163/ai.log)
[ai_trace.log](https://github.com/user-attachments/files/16112164/ai_trace.log)
[code_revisions.log](https://github.com/user-attachments/files/16112165/code_revisions.log)
[error.log](https://github.com/user-attachments/files/16112166/error.log)
[executed_commands.log](https://github.com/user-attachments/files/16112167/executed_commands.log)
[game.log](https://github.com/user-attachments/files/16112168/game.log)
[graphics.log](https://github.com/user-attachments/files/16112169/graphics.log)
[memory.log](https://github.com/user-attachments/files/16112170/memory.log)
[message.log](https://github.com/user-attachments/files/16112171/message.log)
[posted_commands.log](https://github.com/user-attachments/files/16112172/posted_commands.log)
[random.log](https://github.com/user-attachments/files/16112174/random.log)
[received_commands.log](https://github.com/user-attachments/files/16112175/received_commands.log)
[scenario_testing.log](https://github.com/user-attachments/files/16112176/scenario_testing.log)
[sent_commands.log](https://github.com/user-attachments/files/16112177/sent_commands.log)
[setup.log](https://github.com/user-attachments/files/16112178/setup.log)
[system.log](https://github.com/user-attachments/files/16112179/system.log)
[system_debug.log](https://github.com/user-attachments/files/16112180/system_debug.log)
[text.log](https://github.com/user-attachments/files/16112181/text.log)
[time.log](https://github.com/user-attachments/files/16112182/time.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
I appreciate this, its been fixed!
