### ISSUE TITLE
KUR - Annexes Latvia and then returns land to Russia

### ISSUE THREAD

**Issue by Juldris** [kalterkrieg/Kalterkrieg-bug-reports#128]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Sisyphus Declared War Sound, Toolpack + (though it doesn't show up in game), FPS Map, Player-Led Peace Conferences, Coloured Buttons

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None

### Explanation of the Issue

Playing as Germany in 1951, and during the 3WK my puppet Courland annexes Latvia and returns provinces back to Russia and it's puppets

### Steps to reproduce

During the 3WK occupy all of Latvia under Courland control

### Screenshots

![20240705202917_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/108295831/0e67ec2a-e5db-4231-bd15-94394faaa29b)

### Save File

[autosave_temp.zip](https://github.com/user-attachments/files/16112462/autosave_temp.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16112475/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
