### ISSUE TITLE
ENG - Imminent Accord Intervention Useless

### ISSUE THREAD

**Issue by BestestIffers** [kalterkrieg/Kalterkrieg-bug-reports#130]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

plpc

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

toa

### Explanation of the Issue

The Imminent Accord Intervention has no use as Britain is able to call in Canada from the getgo

### Steps to reproduce

Have BWLA rise up and call Canada in

### Possible Cause

Nothing to block ENG from calling allies in 

### Screenshots

![Impending Accord Intervention](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/fe5a3f02-6a11-4363-92fb-56ef4b3c441f)

### Log Files

[error.log](https://github.com/user-attachments/files/16112542/error.log)
[game.log](https://github.com/user-attachments/files/16112543/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
