### ISSUE TITLE
Nation(s) Affected - Summary of Suggestion

### ISSUE THREAD

**Issue by Edes410** [kalterkrieg/Kalterkrieg-bug-reports#132]
<details>
<summary>Please Note (click to expand)</summary>
Suggestions that don't match this template will be closed. We understand this can seem harsh, but in order to ensure we are able to keep on track of bugs other serious issues it is vital our issue tracker is kept organised. The kinds of suggestions that will get close and directed elsewhere include, but are not limited to:
- Anything that suggests adding new content
- Anything that is focused around changing lore
- Anything that will take a significant amount of time to implement
- Anything that isn't specific and actionable change about existing content, as the template specifies
Please know that this isn't out of any disrespect for the ideas you might have for the mod, and encourage people with a passion to get involved either on the subreddit, the discord or even via joining the team itself. But that being said, suggestions that don't match this template will be closed.
</details>

**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1

**Describe the specific change you would like:** In the case of an Accord victory in the Third Weltkrieg, the French Republic should be able to annex Alsace-Lorraine. 

**Explain the reasoning behind this actionable change:** The French Republic still wants the territory back, and considers it no less French than Paris itself. Considering the fact that the Kingdom of Italy is able to gain land that had, up to that moment, been Austrian for centuries, and that Italy, as a unified nation-state, had never owned, in the same peace conference, I see no reason why the Franco-German border should be denied the same treatment. I would even go a step further and say that the French Republic has a much stronger claim over Alsace-Lorraine than the Kingdom of Italy has over the territories of Tyrol, Trieste and Istria. 

**Additional context or comments:** Additionally, the German Empire and the Danubian Federation are states of similar military strength. If Danubia can accept the loss of the aforementioned territories, then so can Germany.

**Comment by Axolotl3823** [comment]
It can annex it if they win and a harsh treaty is signed
