### ISSUE TITLE
NEWS - Coldwell's Return, multiple typos

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#135]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted in green, "Governor-general", is correct. "labour" and "ccf" should be capitalized.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/63903ce8-f7b6-42da-a772-ce083f608148)

**Comment by Flizzyclone** [comment]
did a complete rewrite
