### ISSUE TITLE
Militia takes 500 infantry equipment

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#137]
### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/0b81f7b4-3571-4d1f-8faf-266455cea9c6)
A militia battalion takes up 500 infantry equipment, 5 times more than an infantry battalion

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed. Nice catch!
