### ISSUE TITLE
GER - Starting mechanized units are named "infantry" despite using mechanized namelist

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#138]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: N/A

**Explanation of the issue:**
Germany's starting mechanized units are using infantry names despite the template being set to the mechanized namelist.

**Screenshots:**
![Screenshot 2024-07-05 131806](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/486f365f-4c89-4407-a105-dc43eec555ea)
![Screenshot 2024-07-05 131819](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/b9a497d2-274a-42bf-96ee-b918d14bfcb2)

**Comment by Axolotl3823** [comment]
fixed
