### ISSUE TITLE
All - Naval units namelists

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#139]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1

**Describe the specific change you would like:**
CAL, CAN, DNF, JAP, NEE, NFA, TEX are all missing namelists (or only have one or 2 lists) for naval units.

Meanwhile, GER, ENG and RUS do have namelists but are not assigned to the starting templates. 

**Explain the reasoning behind this actionable change:**
It is really tedious to have to manually add names/assign namelists to the starting templates

**Additional context or comments:**
The tags with missing namelists could simply port over the namelists in Kaiserreich.

**Comment by Axolotl3823** [comment]
fixed
