### ISSUE TITLE
Neurath Returns to Germany - Second paragraph Type

### ISSUE THREAD

**Issue by trooper828xx** [kalterkrieg/Kalterkrieg-bug-reports#14]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: Spot Opt.

**Explanation of the issue:**
Second paragraph, second sentence - awarded is misspelled as awared

**Screenshots:**
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/32004757/359c7478-6c40-49f3-a37c-63cf0cf86e0c)

**Comment by Kennedy2523** [comment]
Fixed.
