### ISSUE TITLE
Infrastructure decreases division speed too much

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#140]
### Explanation of the Issue

In KRG, infrastructure has been increased to 10 per slot, however, the define `NMilitary.INFRASTRUCTURE_MOVEMENT_SPEED_IMPACT` is still at -0.05. So, a state with no infrastructure gives -25% speed in the base game, but it will give -50% speed in KRG. (don't know if this is intended or not, but I'll report it anyways.)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Good catch! Fixed.
