### ISSUE TITLE
ENG - Syndicalist Tensions should not give stability 

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#144]
### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/91652c13-d518-4590-9e5c-baaadc324c7f)
The dynamic modifier can roll over and give positive stability.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
