### ISSUE TITLE
DNF - Danubia not aligned with German Foreign Policy

### ISSUE THREAD

**Issue by sagirismet** [kalterkrieg/Kalterkrieg-bug-reports#146]
### OS

Windows 10 

### HOI4 Version

1.14.7 

### Kalterkrieg Version

release

### List any other mods used

-

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

All except 3 dlc given for free

### Explanation of the Issue

I went the conservative route with the Danube Federation and chose a common foreign policy with Germany.

However, in the proxy wars, I seemed to be on the Entente side. I was unable to send aid to monarchist Morocco and Fengtian.

### Steps to reproduce

Play conservatively with the Danube Federation, and choose a common foreign policy with Germany.

### Possible Cause

Unfortunately, I have no information about this.

### Screenshots

![Ekran görüntüsü 2024-07-06 010550](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171363950/178436a8-2f13-4ee5-98ec-67b477d8421b)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171363950/1662fd89-5f35-440f-a37a-f6e9001b9250)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
