### ISSUE TITLE
GER - Unable to send volunteers to Katanga

### ISSUE THREAD

**Issue by el-helper** [kalterkrieg/Kalterkrieg-bug-reports#148]
(the title wrote itself)
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

1.0

### List any other mods used

Kaiserreich music mod, fps map, modifier icons

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

trial of allegiance

### Explanation of the Issue

i was playing zentrum germay when katanga war broke out, kongo invaded katanga, the event specifies im suportive towards katanga (they even are in my sphere) but i cannot send volunteers as aparently they are my enemies.

### Possible Cause

maybe the diferent ideologies? i am social conservative and katanga authoritarian democracy.

### Screenshots

![Captura de pantalla 2024-07-05 172556](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/112912754/b6a90ff0-e1dc-4d50-92ee-151ca1509508)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by el-helper** [comment]
it seems that it fixed with a couple of weeks?

**Comment by el-helper** [comment]
my volunteers were destroyed and tried to send another ones, the bug appeared again, this time didnt fixed.

**Comment by Kennedy2523** [comment]
@Axolotl3823 was this fixed?

**Comment by Axolotl3823** [comment]
@Kennedy2523 I cant see anyway that loosing your divisions would unallow sending volunteers. With no save or other things to check, and the new changes ive mad to the system i assume its good now
