### ISSUE TITLE
American Union State / Beiyang Government - AUS unable to send volunteers to Beiyang due to unaligned geopolitical goals does not follow previous event.

### ISSUE THREAD

**Issue by ffffffffdsfsdrf3** [kalterkrieg/Kalterkrieg-bug-reports#15]
**Quick questions**
HOI4 version: Latest as of 2024-07-04
Kalterkrieg version: Latest as of 2024-07-04

**Describe the specific change you would like:**
AUS should be able to send volunteers to Beiyang, especially if the AUS send material support through event.

**Explain the reasoning behind this actionable change:**
In 1949 in my playthrough, I was given the option to send 5000 rifles to Beiyang, due to having close relations and geopolitical reasons. Afterwards, I found I was unable to send volunteers to Beiyang through the diplomacy menu due to "not aligning with our geopolitical goals". If the AUS is able to send so many rifles due to geopolitical goals aligning, they should be able to also send volunteers. This should especially be the case if the AUS sends the rifles through the event, as they've already committed to providing support.

**Additional context or comments:**
Perhaps sending the rifles could be the key to a special spirit that allows sending Beiyang volunteers. This in the future could be further expanded, perhaps supporting Beiyang reduces home support but increases influence in some way.

**Comment by Axolotl3823** [comment]
Fixed
