### ISSUE TITLE
Various Suggestions

### ISSUE THREAD

**Issue by Zalipa666** [kalterkrieg/Kalterkrieg-bug-reports#150]
HOI4 version: Bolivar v1.14.7.
Kalterkrieg version: 0.1.
I wrote a detailed review in the Discord (nickname - 😏Ổթℰᗯᛕع✟), consisting of several parts, and one of the administrators asked me to duplicate my suggestions on Github.
Firstly: I suggested changing the regular event that gives one factory so that it gives one factory and two cells to build. I also suggested increasing the limit in NDefines.NBuildings.MAX_SHARED_SLOTS to 2500, in NDefines.NBuildings.MAX_BUILDING_LEVELS to 1250 and in 00_buildings at factories, military plants and shipyards to 1000, in order, again, to make the economic limit almost infinite, which would allow for a truly total and much more interesting war between the player and the bot.
Secondly: I proposed to introduce socialist paths for some countries, such as Russia, Italy, India and China. These may be softer socialists, in Russia we would like to see a Bolshevik way of building Communism.
Thirdly:  I believe that when the eastern puppets of Germany (Ukraine, Lithuania) expand to the east, the Crimean Republic should be created, preferably with its own branch of magic tricks.
And fourthly, what I forgot to write in the Discord: I think it is necessary to introduce scripted peace conferences, which are still not working well.
That's all, thanks, goodbye.

**Comment by MrCovenant000** [comment]
Thank you. Some of this is in the works and the rest we will not be doing but appreciate the suggestion
