### ISSUE TITLE
ENG - Unresearch naval doctrine

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#151]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1

**Describe the specific change you would like:**
ENG should start with no naval doctrine researched at the start of the game.

**Explain the reasoning behind this actionable change:**
ENG has 2 mutually exclusive focuses that reduce the cost of 2 separate naval doctrines. It is also is a bit odd it already has a naval doctrine research (especially since it is the naval supremacy one) when it does not start with a navy.

**Additional context or comments:**
![Screenshot 2024-07-05 161649](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/dc9bed75-0a60-4ecc-ac12-29d5402d102c)
![Screenshot 2024-07-05 161732](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/83d15130-2d90-4441-8b89-1af2dc3c62de)
![Screenshot 2024-07-05 161740](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/04e5bb7e-9891-423e-a2ec-d6c805ff9027)

**Comment by Kennedy2523** [comment]
Fixed.
