### ISSUE TITLE
All - Combined Operations loc issues

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#152]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: N/A

**Explanation of the issue:**
Combined Operations still uses the vanilla mobile warfare text for its description. Also, a doctrine later in the tree is missing loc.

**Screenshots:**
![Screenshot 2024-07-05 163041](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/b9147182-43d9-4cfa-824f-9148227995bc)
![Screenshot 2024-07-05 163216](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/adefbdd7-5a55-4fa5-bbda-471023e11b77)

**Comment by Kennedy2523** [comment]
Already Fixed.
