### ISSUE TITLE
GER - Crash mid-1953

### ISSUE THREAD

**Issue by RoXX047** [kalterkrieg/Kalterkrieg-bug-reports#157]
#  **Quick questions**
OS: Windows 10
HOI4 version: 1.14.7.f4d3
Kalterkrieg version: 0.0.1
List any other mods used: A few cheat mods for fun; "Precise Buffs - Cheat Ideas", ModifierGUI and a few minor visual ones.
Were you using Steam?: Nah.
Were you in multiplayer?: Nope.
Checksum (four-letter code at the bottom of your title menu): b97f
Which expansions do you NOT have?: I have all of them.

### **Explanation of the issue:**
Year is 1953 and it's almost June (20ish of May). American Civil War has been on for some time and i've been supporting the AUS (as Germany). The game's running all fine, focuses work, decision work, events work too but then, but around 25th of May (it crashed on me on 27th of May most of the time), the game crashes instantly.

### **Steps to reproduce:**
1. Simply play to mid-way 1953.

# **Other info:**

### **Possible cause:**
God knows.

### **Log file:**

I will give you both the Logs folder and the folder with the crash to be sure...
[hoi4_20240706_045501.zip](https://github.com/user-attachments/files/16114732/hoi4_20240706_045501.zip)
[logs.zip](https://github.com/user-attachments/files/16114733/logs.zip)

### **Save game:**
Attach a save from before the crash, ideally one where it always happens. A save file is necessary to be able to fix CTDs. Issues without saves will be closed.
[GER_1953_05_19_10.zip](https://github.com/user-attachments/files/16114736/GER_1953_05_19_10.zip)

Have a nice day/night :3

**Comment by Flizzyclone** [comment]
Are you playing a cracked version? Useful for prioritizing.

**Comment by Axolotl3823** [comment]
Also noticeable how a event for Serbia that should have been triggered 35 days in is being triggered for SAF, i think your mods might be screwing with the game too much

**Comment by Axolotl3823** [comment]
This must be due to too many mods or messing with the console command
