### ISSUE TITLE
NEE - Midterms Campaign does not clear "Active Campaign" Flag

### ISSUE THREAD

**Issue by Asratius** [kalterkrieg/Kalterkrieg-bug-reports#161]
### OS

Windows 11

### HOI4 Version

Latest

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich Music Mod, Kaiserreich Model Mods, TNO Style Map

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Allegiance

### Explanation of the Issue

During the Midterms Campaign, after completing a campaign in a state, I could not select that state anymore as the game told me that an active campaign is present blocking me from choosing that ever again during the course of the game even during the next Presidential elections.

### Steps to reproduce

Play from the Midterm Campaign onwards and see how you cannot select the same state anymore even in the presidential election.

### Possible Cause

Probably the completion of a campaign during the midterms does not clear the flag active campaign properly?

### Screenshots

![20240706130120_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/56938438/04a5539a-6c3b-47ed-9a5a-953b7d16fa30)
Screenshot is from the Presidential Campaign after the Midterms

### Save File

I do not have a recent premidterm save but I think they can be triggered manually through event?

### Log Files

[error.log](https://github.com/user-attachments/files/16115753/error.log)
[game.log](https://github.com/user-attachments/files/16115755/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
