### ISSUE TITLE
NEE - Contradictory Events and Elections Results in 1953

### ISSUE THREAD

**Issue by Asratius** [kalterkrieg/Kalterkrieg-bug-reports#162]
### OS

Windows 11

### HOI4 Version

Latest

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich Music Mod, Kaiserreich Model Mods, TNO Style Map

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Allegiance

### Explanation of the Issue

I receive an event whose tooltips states that the Democrats secured the election but then I receive an event proclaiming that Dewey won (I picked Dewey for the 1953 election while having chosen the Democrats previously). I do not know even how the computation for the electoral votes is done because by looking at party popularity in the individual states I think the Democrats should have won?

### Steps to reproduce

Play onwards from the save I provide and look also at the individual States.

### Screenshots

![20240706130946_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/56938438/a23d9f67-ec45-4e25-acb7-3c570b263491)
![20240706130941_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/56938438/3aa2dd1a-d811-4424-829e-6cbd3f1dc26a)

### Save File

[Kalterkrieg - New England 3.zip](https://github.com/user-attachments/files/16115788/Kalterkrieg.-.New.England.3.zip)

### Log Files

[game.log](https://github.com/user-attachments/files/16115790/game.log)
[error.log](https://github.com/user-attachments/files/16115791/error.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
I believe I fixed this, but this is a very weird bug. Good to see you playing the mod Asratius, hope you enjoyed!
