### ISSUE TITLE
NEE - Possibly All Nations - Research Speed for Doctrines Used (Deprecated)

### ISSUE THREAD

**Issue by Asratius** [kalterkrieg/Kalterkrieg-bug-reports#163]
### OS

Windows 11

### HOI4 Version

Latest

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich Music Mod, Kaiserreich Model Mods, TNO Style Map

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Allegiance

### Explanation of the Issue

All the Doctrine Bonuses use "Research Bonus for Land Doctrine" etc. which have been deprecated. The effect should be Cost Reduction for Land Doctrine since they are not anymore Researches but unlocked via Military XP.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
