### ISSUE TITLE
Nation(s) Affected - Summary of Bug

### ISSUE THREAD

**Issue by MrPerson123465** [kalterkrieg/Kalterkrieg-bug-reports#164]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich music mods

### Were you using Steam?

Yes

### Were you in multiplayer?

no 

### Which expansions do you NOT have?

Trial of Allegiance,Arms Against Tyranny,By Blood Alone

### Explanation of the Issue

In the event "Who should we support in Mittleafrika", the options do the opposite of what they will say, as in clicking Krupp will give the event for Hippel and vice versa. Ribentrop workd fine though.

### Steps to reproduce

Play as Germany, Trigger the event "Who should we support in Mittleafrika" which I believe is itself triggered by the Rossing Dossier event chain. The Rossing Dossier is started by event.

### Possible Cause

I think the triggers for strating each event for Mittleafrika got miked up.

### Screenshots

![20240706160222_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174728431/ffd9df34-4fd8-4e74-b409-77c1e1639e73)
![20240706160223_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174728431/1fba360d-e050-4c4b-91d3-0d1233c921bf)
![20240706160224_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174728431/1aaed672-9cc6-408b-8214-751a3f1114da)

### Important Files Attached

- [ ] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed, thank you
