### ISSUE TITLE
GER - DkP can not win the 1951 elections no matter what

### ISSUE THREAD

**Issue by MrPerson123465** [kalterkrieg/Kalterkrieg-bug-reports#167]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich music mods, FPS map(no coloured icons or strategic view adjustment)

### Were you using Steam?

Yes

### Were you in multiplayer?

no 

### Which expansions do you NOT have?

Trial of Allegiance,Arms Against Tyranny,By Blood Alone

### Explanation of the Issue

When getting the event of 1951 elections for the die Große Koalition route, no matter what, Zentrum will always win, soft-locking the player from the DkP route. This will happen even if you use commands to do all decisions which boost DkP popularity beyond what is normally possible, they will still lose. I also tried increasing Reichstag and Bunderstat support, but this changed nothing.

### Steps to reproduce

1)Go down the Große Koalition focus path, in this configuration:
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174728431/e2e21a7a-53f5-4cbc-8728-92f7cb3c58f3)
2)Wait for the 1951 elections.
3)Attempt to increase DkP popularity by decision

### Possible Cause

I think the events don't actually do anything, as the text constantly says"Zentrum is favored to win the elections currently" no matter what I do.

### Screenshots

![20240706171741_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174728431/d5c8e9b1-dffd-4263-b385-3ad2d3448329)
Here you can see there are no available decisions, as I took them all already.

### Save File

Start of elections(This is where I saved for the North Sea exercise, so just do the options that avoid war. Also, Latvia will declare war on you sometime later):
[GER_1951_03_12_11.zip](https://github.com/user-attachments/files/16116782/GER_1951_03_12_11.zip)

Near end of elections:
[GER_1951_04_10_09.zip](https://github.com/user-attachments/files/16116770/GER_1951_04_10_09.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16116772/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by MrPerson123465** [comment]
Also, i'm not sure, but I think that the reverse is also true: choosing to side with Zentrum will result in DkP winning, but i'm not sure.

**Comment by MrPerson123465** [comment]
I have played a new game but this time siding with Zentrum and I can say that no matter what Zentrum will win.

**Comment by Axolotl3823** [comment]
@Texican-BC This is my fault ill fix it
