### ISSUE TITLE
NOR - Music Suggestion

### ISSUE THREAD

**Issue by Steffplays123** [kalterkrieg/Kalterkrieg-bug-reports#168]
**Quick questions**
HOI4 version: All
Kalterkrieg version: All with the Music Mod

**Describe the specific change you would like:**
Add Norway specific music from the late 1940s to 1960s in the Music Mod:
- Alle vakre jenters hambo (All beautiful girls' hambo) - Nora Brockstedt & Anders Saus
- Tango for to (Tango for two) - Alf Prøysen & Torhild Lindal (1950s hit)
- Frihetens forpost (Outpost of Freedom) - Erling Krogh or Grex Vocalis (Second World War-era socialist song)
- Voi-voi - Nora Brockstedt (1960 Eurovision song)
- Når kastanjene blomstrer (When the chestnuts bloom) - Jens Book-Jenssen
- Blåveispiken (Liverleaf girl) - Kurt Foss & Reidar Bøe
- De nære ting (The close things) - Kurt Foss & Reidar Bøe

Some singers from the era to be aware off:
- Kurt Foss, Reidar Bøe, Nora Brockstedt, Alf Prøysen, Jens Book-Jenssen (Norway's Bing Crosby), Leif Juster, Einar Rose

**Explain the reasoning behind this actionable change:**
The Norwegian music here is some of those from the era of Kalterkrieg, and I believe some of them could be a good fit in the Music Mod. With the singers listed, you can also look around in their performances for other songs.

**Additional context or comments:**

**Comment by Ymerein** [comment]
Added to our list. Thank you for the suggestions!
