### ISSUE TITLE
Finland - Useless modifiers

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#17]
### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/079e99c3-4ead-437b-b3aa-9d3e1ab74d6f)
`recruitable_population` is a state modifer, `conscription` should be used on ideas.
This idea doesn't give any extra manpower as of right now.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
