### ISSUE TITLE
USA, Ottoman empire, North France, etc. - puppeted in the peace conference

### ISSUE THREAD

**Issue by zhenya-doma** [kalterkrieg/Kalterkrieg-bug-reports#176]
**Quick questions**
OS: Windows 10
HOI4 version: v1.14.7.f4d3
Kalterkrieg version: v 0.1
List any other mods used: Kaiserreich music, Kaiserreich music Internacionales, Kaiserreich music Kaisercat, Kaiserreich models from all DLCs + Base game, Kalterkrieg, Kalterkrieg Models - Kaiserreich models compatibility Submod
Were you using Steam? Yes
Were you in multiplayer? No
Which expansions do you NOT have? BBA, AAT, ToA

**Explanation of the issue:**
Sorry for my broken English, it's not my native language.
1. Nations in a peace conference can puppet defeated nations (2 puppeted CSAs, 2 puppeted AUSs, puppeted northern France and Ottomans and other nations). I suppose it's NOT intended in this mod.
2. For some reason, I didn't recieve any events to release occupied nations as puppets after the war.
**Steps to reproduce:**
I didn't take any specific steps to summon these issues, I was just playing the game
**Other info:**
1. Tank models are the same for all nations.
2. Durind WW3 Belarus popped up, even though in the beginning of the game (I was playing as Russia) I made a deal with Germany that I retain control over the Baltic states and Belarus and only cede left bank Ukraine to the Reichspakt.
3. After the liberation of some cities, for example, Barcelona, an event about the fall of such city occured.
**Possible cause:**

**Log file:**

**Screenshots / Video:**

![20240706225611_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/150959426/35469476-9d9a-4cde-8146-b4fc5fcf148e)
![20240706230144_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/150959426/d37c1252-e010-496f-851d-b8409cf3ee80)
![20240706232729_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/150959426/c0023d8a-c980-43e2-b322-fbc0654abe9e)
![20240706210444_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/150959426/86077d57-da45-4987-9a5c-54f2254e5207)

**Save game:**

[New Russia_temp_temp.zip](https://github.com/user-attachments/files/16117459/New.Russia_temp_temp.zip)

**Comment by zhenya-doma** [comment]
Logs:
[game.log](https://github.com/user-attachments/files/16117534/game.log)
[error.zip](https://github.com/user-attachments/files/16117537/error.zip)

**Comment by Axolotl3823** [comment]
"fixed" this cant happen anymore at least
