### ISSUE TITLE
In France, in 1949, I'm making plans for 1948

### ISSUE THREAD

**Issue by sagirismet** [kalterkrieg/Kalterkrieg-bug-reports#178]
**Quick questions** 
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: -

**Explanation of the issue:**
As you can see, the year is 1949 but we are making the 1948 Plan.

To prevent such a thing from happening, the date section in focus can be set to change according to the current year.
I think focus names changed depending on the date in the Kaiserreich, so I think you can do it.

**Screenshots:**
![Ekran görüntüsü 2024-07-07 135735](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171363950/b050824b-68af-4fe2-a208-d149fb74031c)

**Comment by thelilh** [comment]
Thank you, will fix this! 😊

**Comment by thelilh** [comment]
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/36357091/c8552895-02b7-45fb-9b5a-0ecad2458829)
Fixed 😄
