### ISSUE TITLE
LAT - Latvia apearing in the Russian civil war despite Latvia not existing

### ISSUE THREAD

**Issue by MrPerson123465** [kalterkrieg/Kalterkrieg-bug-reports#180]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich music mods

### Were you using Steam?

Yes

### Were you in multiplayer?

no 

### Which expansions do you NOT have?

Trial of Allegiance,Arms Against Tyranny,By Blood Alone

### Explanation of the Issue

When Germany does the Continuation war and wins, Kourland annexes Latvia. And during the Russian civil war, Latvia is supposed to take Dvinsk from Russia, but if there is no Latvia already there, it creates Latvia in the province.

### Steps to reproduce

1) As Germany, do the continuation war and win.
2) Wait for the Russian CIvil War, where Latvia will spawn.

### Possible Cause

There seems to be no check for if Latvia exists or not. I think that if it doesn't, Dvinsk should either stay Russian or transfer to Kurland.

### Screenshots

![Uploading 20240707150518_1.jpg…]()
![Uploading 20240707150530_1.jpg…]()

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
