### ISSUE TITLE
TEX - North Dakota Should Be Progressive

### ISSUE THREAD

**Issue by ForTheImperium** [kalterkrieg/Kalterkrieg-bug-reports#181]
HOI4 version: 1.14.7
Kalterkrieg version: 0.1

I'd suggest making North Dakota far more progressive and adding a NPL state modifier like Sid McMath's. One small update could totally do the trick.
Governor: AFP (C)--> AFP (P)
Senate: 1 AFP (C), 1 AFP (O) --> 2 AFP (P)
House: 2 AFP (C)--> 2 AFP (P)

A party of progressive liberals, progressives, and even socialists, the NPL was almost dominating ND politics at the time, and it could fit into the progressive faction of AFP rather well - definitely not AFP (C). As an easy way out, you can just throw people with ties to it into AFP (P): Quentin Burdick, Milton Young, William Langer, William Lemke, etc. I think someone actually asked about and suggested a similar thing in ask-a-dev last year and got a yes from Leaf, but nothing seems to have been changed; I guess Leaf has been too busy doing other stuff and just forgot about this?

**Comment by thelilh** [comment]
I did not remember saying yes to this a year ago, but it's now changed 😄
