### ISSUE TITLE
DNF - Event: The New World, and our place within it, capitalization

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#182]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:

0.1
List any other mods used:
None

**Explanation of the issue:**
Every word in the title except "and" should be capitalized.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/18a5bc86-d563-4525-ae02-6f5c9a16d7ec)

**Comment by thelilh** [comment]
Fixed
