### ISSUE TITLE
DNF - Tildy government focus trees overlap

### ISSUE THREAD

**Issue by ComDiehard** [kalterkrieg/Kalterkrieg-bug-reports#183]
### OS

Windows 10

### HOI4 Version

Most recent

### Kalterkrieg Version

Most recent

### List any other mods used

No

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Only got mtg and LR

### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/73826820/2dfc3fb7-9539-4068-98ca-51dfc84f67a7)
Won the 1955 elections as tildy, new focus tree loaded over the old. 

### Steps to reproduce

Play DNF conservatives untill 1955, elect tildy and normally this should happen

### Save File

[autosave.zip](https://github.com/user-attachments/files/16120161/autosave.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16120164/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
