### ISSUE TITLE
DNF - Event: Meeting with the Austrian School, clunky sentence

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#184]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, the quote doesn't work here.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/4a527a0d-4cdb-4047-8fa2-b3886680d11e)

**Comment by kandis125** [comment]
Fixed it, re-worded it
