### ISSUE TITLE
TEX - Wrong Election Speech 

### ISSUE THREAD

**Issue by TheAdrianbbc** [kalterkrieg/Kalterkrieg-bug-reports#185]
### OS

Windows 10

### Were you using Steam?

No

### Were you in multiplayer?

No

### Explanation of the Issue

Progressives won the first AUS election and Russel should give a speech before election not Earl.  Also Sid McMath has the same introduction on 2nd term as on the first term.   

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/5848cf9e-960c-49cf-b476-00d5dcfbcb69)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by TheAdrianbbc** [comment]
2' nd  American Civil war is also bugged . As AUS I revealed  New England Pennsylvania plot via decision. It resumed civil war  and gave me decision to declare war or to accept stalemate in Pennsylvania.    I chose the later  and  it didn't stop a war.

**Comment by thelilh** [comment]
> 3' rd American Civil war is also bugged . As AUS I revealed New England Pennsylvania plot via decision. It prematurly started civil war and gave me decision to declare war or to accept stalemate in Pennsylvania. I chose the later and it didn't stop a war. The decison starts bugged Third a American civil war if you press it in the next month.

make a new issue for this

**Comment by TheAdrianbbc** [comment]
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/dfa9cd54-a04c-4d8f-b723-34ef1f42506c)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/9028d0a7-1560-4a38-a1b6-76e97b67d879)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/616e079f-9b50-4ddf-98aa-77b6793c592c)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/6e02505c-6339-40b8-9849-2d555253ea8c)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/dd581908-05c9-4bbc-b50c-bb0ac823c073)

**Comment by thelilh** [comment]
Again. Make a new issue for the American Civil War. This is for one issue, not multiple

**Comment by TheAdrianbbc** [comment]
Done  Sorry it took me these long but I didn't want to do screenshots again

**Comment by thelilh** [comment]
Fixed
