### ISSUE TITLE
TEX- Bugged Third Amercian Civil w

### ISSUE THREAD

**Issue by TheAdrianbbc** [kalterkrieg/Kalterkrieg-bug-reports#186]
### OS

Windows 10

### Were you using Steam?

No

### Were you in multiplayer?

No

### Explanation of the Issue

As AUS I revealed New England Pennsylvania plot via decision. It prematurly started civil war and gave me decision to declare war or to accept stalemate in Pennsylvania. I chose the later and it didn't stop a war. The decison starts bugged Third a American civil war if you press it in the next month.

### Steps to reproduce

1. When you get your second  event for Pennsylvania Plot as AUS chose : We Must remain Quiet option
2. Use the decision Expose Operation Gray Eyes after you start the next month.
3. It starts Civil war that you can't deescalate.

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/dfa9cd54-a04c-4d8f-b723-34ef1f42506c)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/9028d0a7-1560-4a38-a1b6-76e97b67d879)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/616e079f-9b50-4ddf-98aa-77b6793c592c)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/6e02505c-6339-40b8-9849-2d555253ea8c)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/8d68d89e-61b8-492b-81b9-35aae1819e54)

### Save File

[TEX_1952_10_19_01.zip](https://github.com/user-attachments/files/16120438/TEX_1952_10_19_01.zip)

### Log Files

[ai_trace.log](https://github.com/user-attachments/files/16120442/ai_trace.log)
[code_revisions.log](https://github.com/user-attachments/files/16120443/code_revisions.log)
[error.log](https://github.com/user-attachments/files/16120441/error.log)
[executed_commands.log](https://github.com/user-attachments/files/16120450/executed_commands.log)
[executed_commands.log](https://github.com/user-attachments/files/16120451/executed_commands.log)
[game.log](https://github.com/user-attachments/files/16120453/game.log)
[game.log](https://github.com/user-attachments/files/16120452/game.log)
[graphics.log](https://github.com/user-attachments/files/16120455/graphics.log)
[graphics.log](https://github.com/user-attachments/files/16120456/graphics.log)
[memory.log](https://github.com/user-attachments/files/16120457/memory.log)
[memory.log](https://github.com/user-attachments/files/16120458/memory.log)
[message.log](https://github.com/user-attachments/files/16120459/message.log)
[message.log](https://github.com/user-attachments/files/16120460/message.log)
[posted_commands.log](https://github.com/user-attachments/files/16120461/posted_commands.log)
[posted_commands.log](https://github.com/user-attachments/files/16120462/posted_commands.log)
[random.log](https://github.com/user-attachments/files/16120463/random.log)
[random.log](https://github.com/user-attachments/files/16120464/random.log)
[random_1.log](https://github.com/user-attachments/files/16120465/random_1.log)
[random_1.log](https://github.com/user-attachments/files/16120466/random_1.log)
[random_2.log](https://github.com/user-attachments/files/16120467/random_2.log)
[random_2.log](https://github.com/user-attachments/files/16120468/random_2.log)
[random_3.log](https://github.com/user-attachments/files/16120469/random_3.log)
[random_3.log](https://github.com/user-attachments/files/16120470/random_3.log)
[random_4.log](https://github.com/user-attachments/files/16120471/random_4.log)
[random_4.log](https://github.com/user-attachments/files/16120472/random_4.log)
[random_5.log](https://github.com/user-attachments/files/16120473/random_5.log)
[random_5.log](https://github.com/user-attachments/files/16120474/random_5.log)
[random_6.log](https://github.com/user-attachments/files/16120475/random_6.log)
[random_6.log](https://github.com/user-attachments/files/16120476/random_6.log)
[received_commands.log](https://github.com/user-attachments/files/16120477/received_commands.log)
[received_commands.log](https://github.com/user-attachments/files/16120478/received_commands.log)
[scenario_testing.log](https://github.com/user-attachments/files/16120480/scenario_testing.log)
[scenario_testing.log](https://github.com/user-attachments/files/16120479/scenario_testing.log)
[sent_commands.log](https://github.com/user-attachments/files/16120481/sent_commands.log)
[sent_commands.log](https://github.com/user-attachments/files/16120482/sent_commands.log)
[setup.log](https://github.com/user-attachments/files/16120483/setup.log)
[setup.log](https://github.com/user-attachments/files/16120484/setup.log)
[system.log](https://github.com/user-attachments/files/16120485/system.log)
[system.log](https://github.com/user-attachments/files/16120486/system.log)
[system_debug.log](https://github.com/user-attachments/files/16120487/system_debug.log)
[system_debug.log](https://github.com/user-attachments/files/16120488/system_debug.log)
[text.log](https://github.com/user-attachments/files/16120489/text.log)
[text.log](https://github.com/user-attachments/files/16120490/text.log)
[time.log](https://github.com/user-attachments/files/16120491/time.log)
[time.log](https://github.com/user-attachments/files/16120492/time.log)
[ai.log](https://github.com/user-attachments/files/16120493/ai.log)
[ai.log](https://github.com/user-attachments/files/16120494/ai.log)
[ai_trace.log](https://github.com/user-attachments/files/16120495/ai_trace.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
