### ISSUE TITLE
DNF - Dealing with Dollfuss, double space, minor typos, word choice

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#187]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, double space between "Hardliner" and "wing", "enlargment" should be "enlargement", "it's" should be "its", IMO "was" should be "were to be", 

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/2e94810d-8f14-40fc-b8b5-a8621405ce31)

**Comment by thelilh** [comment]
Fixed
