### ISSUE TITLE
DNF - Focus: Spending For Peacetime, missing word

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#188]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, "that" should be written between "now" and "we're".

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/0ba7d306-2562-4bcc-8b83-2fb34c751719)

**Comment by thelilh** [comment]
Fixed
