### ISSUE TITLE
TEX - Incorrect number of Senators under Congress decision

### ISSUE THREAD

**Issue by ffffffffdsfsdrf3** [kalterkrieg/Kalterkrieg-bug-reports#19]
**Quick questions**
HOI4 version: Latest as of 2024-07-04
Kalterkrieg version: Latest as of 2024-07-04

**Explanation of the issue:**
Under Events and decisions, there is supposedly 72 senators, 33 for the conservatives, but this does not add up when you add them. Further explanations will be seen in screenshots.

**Screenshots:**
![hoi4_8](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/92403179/f6a68769-585f-4479-ade4-751cdbb308d5)

29/72 senators makes majority, clearly incorrect.

the 29 senators total for a majority, makes sense wit the  20/20 orthodox and 9/9 Progressive senators add up - perfectly fine.

The 33 conservative senators and the remaining 43 total (supposedly conservative) senators do not add up - Incorrect addition

It seems extra senators have been added to the conservatives and total senator numbers.

**Comment by thelilh** [comment]
Will fix in next patch. 248 and 72 was basically a "magic number" if you will

**Comment by thelilh** [comment]
![20240709223756_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/36357091/9b308429-27e3-4a47-8b4f-095e66563c05)
