### ISSUE TITLE
Germany et al - Against spelled Agisnt 

### ISSUE THREAD

**Issue by Tedreyer99** [kalterkrieg/Kalterkrieg-bug-reports#192]
**Quick questions**
HOI4 version: Earliest as of 2024-07-07
Kalterkrieg version: Latest on Steam
List any other mods used: State transfer Tool

**Explanation of the issue:**
1st paragraph, bottom right; "Joined" the Allied Powers _agisnt_

**Screenshots:**
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174970026/d66beac9-aca7-4a6b-bb5c-d7688efbe803)

**Comment by Tedreyer99** [comment]
Switzerland Announces the Haute-Savoie Conference 

That's the name of the news popup.

**Comment by thelilh** [comment]
Fixed
