### ISSUE TITLE
NEE- Suggests around economy 

### ISSUE THREAD

**Issue by flavidus-aurelius** [kalterkrieg/Kalterkrieg-bug-reports#193]
<details>
<summary>Change Baldwin Path New England Focuses to Have an Effect</summary>
</details>

**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: .1

**Describe the specific change you would like:**
Change the focuses affecting the Economic Boom spirit to create a new spirit, or change the Delaware Commission event to not bypass these focuses.

**Explain the reasoning behind this actionable change:**
Currently, since Delaware commission removes the spirit after the 1949 election, these focuses can never be taken. Instead, they are either bypassed or immediately have their effects improving the spirit removed. This way, the focuses have an effect that makes the Baldwin path symmetrical to the Harrison path.

**Additional context or comments:**

**Comment by Kennedy2523** [comment]
Im sorry, I dont understand your suggestion clearly. The economic boom wears off on its own as the new states are added, that is intended.
