### ISSUE TITLE
Nation(s) Affected - Summary of Typo

### ISSUE THREAD

**Issue by Adil1-source** [kalterkrieg/Kalterkrieg-bug-reports#195]
**Quick questions**
HOI4 version: None
Kalterkrieg version: Idk
List any other mods used: None

**Explanation of the issue:**

Casablanca is misspelled

**Screenshots:**

![20240708213137_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175056452/f99e51d4-e072-47b4-b2f6-885143d1f83c)

**Comment by MrCovenant000** [comment]
Fixed
