### ISSUE TITLE
South France Wrong Name

### ISSUE THREAD

**Issue by Trikelol** [kalterkrieg/Kalterkrieg-bug-reports#196]
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: kaisercat music

french community route names you the french union

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175068193/65396d41-37f9-46db-933d-f829f97fbf64)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175068193/7d2284db-71e1-4922-b99d-cebe475fe415)

**Comment by Kennedy2523** [comment]
This is WAD. I know it's confusing but it's historical
