### ISSUE TITLE
NEE - Dewey Always wins in 1953

### ISSUE THREAD

**Issue by Kennedy2523** [kalterkrieg/Kalterkrieg-bug-reports#198]
### OS

Windows 10

### Were you using Steam?

No

### Were you in multiplayer?

No

### Explanation of the Issue

From reddit: Dewey wins every time in 1953 even if you get majority democrat electoral votes. Like you’ll get the event that says the democrats have won but every single time Dewey gets inaugurated for no reason.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
For the public to know, this critical bug has now been fixed
