### ISSUE TITLE
TEX - Holt can't be elected as President

### ISSUE THREAD

**Issue by pleasehelpthis** [kalterkrieg/Kalterkrieg-bug-reports#199]
### OS

Windows 10

### HOI4 Version

Latest

### Kalterkrieg Version

Latest Bolivar v1.14.7.f4d3

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

All Latest except for trial of allegiance

### Explanation of the Issue

Cant elect any other faction members tried electing Conservative Holt never got inaugurated into presidency.

### Steps to reproduce

Try electing Holt by choosing each event to give him majority 

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Should be fixed with next patch
