### ISSUE TITLE
GER - Beiyang Volunteers

### ISSUE THREAD

**Issue by Doc01945** [kalterkrieg/Kalterkrieg-bug-reports#20]
### OS

Windows 11

### HOI4 Version

1.14.6

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich Music Mod, Kaiserreich Graphical Overhaul

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

As Germany, I had one (1) tank division sent to the Beiyang Government in the CCW. After Madagascar became independent in January 1950, I noticed that my division was suddenly in Germany but still under the ''Chinese volunteers'' theatre. Furthermore, the entire Entente and Reichspakt sent divisions to the side they support respectively. I have withdrawed my division from Beiyang.

### Steps to reproduce

- As Germany, send a volunteer division to Beiyang.
- Wait until Madagascar becomes independent.
- Notice the issue I have described. 

### Possible Cause

Madagascar becoming independent. 

### Screenshots

![Schermafbeelding 2024-07-04 165623](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130096105/5bbc19b0-71da-4795-b103-a32f61f000bf)
![Schermafbeelding 2024-07-04 165705](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130096105/7b74edd9-0ef0-414a-b14c-93eeb964dd1a)

### Save File

[autosave.zip](https://github.com/user-attachments/files/16100512/autosave.zip)

### Log Files

[error.log](https://github.com/user-attachments/files/16100549/error.log)
[game.log](https://github.com/user-attachments/files/16100550/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by DankestGhost** [comment]
![Screenshot 2024-07-04 083148](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/83197242/49581de8-d2fe-4ba5-aa65-d9f58c5fd37d)
This seems to have happened to me as well when I was playing New England. Madagascar beccame independent then my divisions to china seem to have left
