### ISSUE TITLE
Paris revolt, Germany - Germany nukes paris during their revolt

### ISSUE THREAD

**Issue by lhafjhdsjhfkadshfkhlfhlkje234** [kalterkrieg/Kalterkrieg-bug-reports#200]
### OS

Windows 10

### HOI4 Version

Latest

### Kalterkrieg Version

0.1

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Explanation of the Issue

AI Germany nuked paris during the paris revolt in North France in 1956. I'm sorry if this is normal or just gameplay reasons but I find it non logical for Germany to nuke its allys capital city  despite the whole revolt happening. Maybe there could be a fix to prevent the ai from using nukes during this specific war in case its not intended to happen.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by MrCovenant000** [comment]
Unfortunately we are currently limited by PDX and cannot control when the ai nukes nations. We may turn down generation rate of nukes but the only other option is to disable them until the nuke rework comes to hoi4
