### ISSUE TITLE
EST - Savinkovist Military Occupation Regime under Germany

### ISSUE THREAD

**Issue by Caliburxd** [kalterkrieg/Kalterkrieg-bug-reports#201]
**Quick questions**
OS: Not related
HOI4 version: Not related
Kalterkrieg version: 0.1.1
List any other mods used: Only GFX and music mods
Were you using Steam?: Yes
Were you in multiplayer?: Nope
Which expansions do you NOT have?: I have all

**Explanation of the issue:**
When the Continuation War between Russia and Germany ends, if Germany wins, Estonia shifts to Reichspakt and becomes a puppet under the name 'Military Occupation Regime' but is still National Populist -> Savinkovist and the leader is the same, not a military leader.

**Steps to reproduce:**

1. Germany wins the Continuation War

**Other info:**
Estonia does not have a custom focus tree but a generic one. It wouldn't make much of a difference if it changes its ideology and won't break the game in my opinion.

**Possible cause:**
Estonia doesn't really becomes a puppet of Germany, it is scripted.

**Log file:**

Not neccessary
**Screenshots / Video:**

https://prnt.sc/WL5uIhkdaegB
**Save game:**

Not neccessary

**Comment by thelilh** [comment]
This is now fixed
