### ISSUE TITLE
GER + NAM - Wilhelm III instead of IV

### ISSUE THREAD

**Issue by Doc01945** [kalterkrieg/Kalterkrieg-bug-reports#202]
**Quick questions**
HOI4 version:
- 1.14.6

Kalterkrieg version:
- 0.1.1

List any other mods used:
- Kaiserreich Graphical Overhaul
- Kaiserreich Music Mod

**Explanation of the issue:**
I'm in early 1951, playing as Germany. The ''Referendum Cancelled in South West Africa'' mentions Wilhelm IV, but he is not the Kaiser yet. 

**Screenshots:**
![Schermafbeelding 2024-07-09 123605](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130096105/9c2d6ba8-70a7-4129-97d6-d4ea1f7ddd30)

**Comment by thelilh** [comment]
Fixed, will be in next patch
