### ISSUE TITLE
CAN - A slash sign instead of period sign in text event of Debate on Bill C-22 Begins

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#205]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: Kalterkrieg Models and All Kaiserreich Models

**Explanation of the issue:**
There is a slash sign instead of placing a period sign after the word "Ententist" in the text event of Debate on Bill C-22 Begins. 

**Screenshots:**
![Image_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/131833099/aacd2e81-d845-42e5-8bf4-ae607db5c3d8)

**Comment by thelilh** [comment]
Fixed
