### ISSUE TITLE
DNF - Event: The Minister-President Race Begins, extra word

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#207]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, one of the "the" should be removed for a better sentence structure.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/04c36a12-ea74-47c1-b39c-1fdabde16d05)

**Comment by thelilh** [comment]
Fixed
