### ISSUE TITLE
DNF - Event: Matters of Europe, missing word, "it's", typos

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#208]
**Quick questions**
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, should be a "of" between "one" and "a", "Further more" should be "Furthermore", "it's" should be "its", "musn't" should be "mustn't".

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/e54507aa-d395-4e62-8e7f-7ea6558c8ba9)

**Comment by thelilh** [comment]
Fixed
