### ISSUE TITLE
DNF - Event: Tildy Zoltán Elected Christian-Bloc Leader, minor typo

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#209]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, "truely" should be "truly".

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/d4231f6c-6eac-4276-98ec-28317c859ed0)

**Comment by thelilh** [comment]
Fixed
