### ISSUE TITLE
MAF - MAF_MAG_conflict has no localization

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#210]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Possible Cause

Probably need localization.

### Screenshots

![Image_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/131833099/d25c84a8-802b-4e2d-a851-1f2468c56354)

### Save File

[MAF.zip](https://github.com/user-attachments/files/16145138/MAF.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Thank you, we've now fixed this! Will be released in 0.1.2.
