### ISSUE TITLE
Germany - game crashes when unpause autosave

### ISSUE THREAD

**Issue by faceclanpro1** [kalterkrieg/Kalterkrieg-bug-reports#212]
**Quick questions**
OS: win 11
HOI4 version: 1.14.7
Kalterkrieg version: newest one as of 10 July
List any other mods used: none
Were you using Steam? yes
Were you in multiplayer? no
Checksum (four-letter code at the bottom of your title menu): 5bb4
Which expansions do you NOT have? Man the guns, La resistance, battle for bosphorus, no step back, by blood alone, arms against tyranny

**Explanation of the issue:**
I load a savegame, and it always crashes 2 in game hours after unpausing

**Steps to reproduce:**

1. unpause game

2. crash

**Other info:**

**Possible cause:**

**Log file:**

https://github.com/user-attachments/files/16146990/logs.zip

**Screenshots / Video:**

**Save game:**
Attach a save from before the crash, ideally one where it always happens. A save file is necessary to be able to fix CTDs. Issues without saves will be closed.
https://github.com/user-attachments/files/16146971/game.crash.zip

**Comment by Flizzyclone** [comment]
Hi, was this save done entirely on the newest version? The patch did break saves.

**Comment by faceclanpro1** [comment]
> Hi, was this save done entirely on the newest version? The patch did break saves.

Oh, yeah I started my game before the patch on July 9. so is there a way to fix it or for me to go back to the old patch?

**Comment by Flizzyclone** [comment]
Not aware of any way to do so through steam, sorry. Closing this for our tracking purposes.
