### ISSUE TITLE
GER - Naval base still in the wrong spot

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#214]
**Quick questions**
OS: Windows 11
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: N/A
Were you using Steam? Yes
Were you in multiplayer? No
Which expansions do you NOT have? Trial of Allegiance

**Explanation of the issue:**
The Wilhemshaven naval base is still located on Heligoland despite patchnotes saying it is fixed.

**Screenshots:**
Where it is and where it should be:
![Screenshot 2024-07-09 174808](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/a1512cc4-d191-42af-a8ef-f28f96d171c2)
How it looks in Kaiserreich:
![Screenshot 2024-07-09 175421](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/6b709cf7-fa8d-4a8b-be91-5f222f141eb8)

**Comment by Flizzyclone** [comment]
Properly fixed internally now, our bad.
