### ISSUE TITLE
New England - Game crashing on unpause of load of manually saved game

### ISSUE THREAD

**Issue by secondisland** [kalterkrieg/Kalterkrieg-bug-reports#216]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

8th July update (not sure how to find version)

### List any other mods used

None

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Allegiance

### Explanation of the Issue

Loaded my New England save game, tried to un-pause it but HOI IV crashed out to desktop. I tried this a second time and got the same result.

I started this game after the latest patch was released after noting it would break previous save games.

I've added the error log, but have copied and saved the system and game log files as well in case they would be of any help: please let me know if so.

### Steps to reproduce

As above, though I loaded directly from the launcher rather than via the in-game menu.

### Save File

[NEE_1952_01_11_01.zip](https://github.com/user-attachments/files/16158599/NEE_1952_01_11_01.zip)

### Log Files

[error.zip](https://github.com/user-attachments/files/16158635/error.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
looking at your errors it appears the save was made in the old version. You might have gotten confused as it is hard to spot if the game had updated or not. We are working on a banner like KR to make it clearer going forward. You will need to start a new game as there currently is no way to roll back to the old version.

Sincerely Axolotl

**Comment by secondisland** [comment]
> looking at your errors it appears the save was made in the old version. You might have gotten confused as it is hard to spot if the game had updated or not. We are working on a banner like KR to make it clearer going forward. You will need to start a new game as there currently is no way to roll back to the old version.
> 
> Sincerely Axolotl

Thanks for getting back to me so quickly. I started a new game yesterday as the United Kingdom too and noticed the general election scrubbed all the focuses so assumed the patch borked that and started a second new game as New England. Maybe Steam was being funny following the takedown coming back up and you guys putting a patch out?

Anyway, again, thanks for getting back to me and I really appreciate the work that's being put in to this mod. I'm enjoying it!
