### ISSUE TITLE
CAN - Descriptions of Accord Voting are overlapping when moving down the decision scroll bar

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#217]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

Yes

### Which expansions do you NOT have?

No, I have all

### Explanation of the Issue

When the issue is taken in the Accord Voting and scrolling down the decision tab, the descriptions of issue is somewhat overlapping outside the decision tab. 

### Steps to reproduce

1. Play as CAN.
2. Unlocking Accord Voting decisions.
3. Has issue in Accord Voting.
4. Scroll down the decision tab.

### Possible Cause

I don't know.

### Screenshots

![Image_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/131833099/14c7e651-e92f-4a5c-9e76-b6aa6e84ace1)

### Save File

[CAN.zip](https://github.com/user-attachments/files/16160184/CAN.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
I am really tempted to put this down as a game issue. I will look into it regardless but nothing in the UI specifically should be causing this.

**Comment by Flizzyclone** [comment]
Yeah I think this is something to do with HOI handling scrolling text badly. Can reproduce on other UIs.
