### ISSUE TITLE
Great Britain - Eden comes back to life

### ISSUE THREAD

**Issue by Regularite** [kalterkrieg/Kalterkrieg-bug-reports#22]
### OS

Win11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

None

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Battle for Bosphorus and Trial of Allegience

### Explanation of the Issue

There was event of Eden assassination, then after comes event of Conservatives winning elections with Eden as PM.

### Save File

[save.zip](https://github.com/user-attachments/files/16100703/save.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
I believe this is WAD. He is shot, he isnt assassinated so he recovers.

**Comment by Axolotl3823** [comment]
Eden doesn't die from being shot. He can only die later due to complications
