### ISSUE TITLE
NEWS - Marseille announces its Government, capitalization

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#220]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1.1

List any other mods used:
None

**Explanation of the issue:**
In the title, "announces" should be "Announces".

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/6e686de0-c61e-460a-b99f-fbe14d90a1c5)

**Comment by thelilh** [comment]
Fixed
