### ISSUE TITLE
NEWS - Labor wins the 1948 Australasian elections, capitalization and clunky sentence

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#221]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1.1

List any other mods used:
None

**Explanation of the issue:**
In the title, "wins" and "elections" should be capitalized. Highlighted, "their" doesn't work when Ben Chifley is the sentence subject, IMO just removing it would work.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/3df0e845-eafe-47ad-ae47-89e6672b1391)

**Comment by Githhubcode** [comment]
They -> he
already they -> they are, as expected
