### ISSUE TITLE
TEX - Workshop page and game menu clashing in amount of content done

### ISSUE THREAD

**Issue by CrazyWhatzthis** [kalterkrieg/Kalterkrieg-bug-reports#223]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: The "HOT" Key

**Explanation of the issue:** In-game on the brief history part of the menu, it says that the american union state has full content to 1956, while the workshop page says it has only partial completion (the image with the "content on release" also has it, but since I didn't have the mod on release due to the DMCA stuff, it may be accurate, which means it wouldn't have to be changed (then again, the in-game version can be wrong too))

**Screenshots:** 
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175259984/5f800b38-bce4-490d-bde8-8e762cfebd21)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175259984/7f2cbb0f-fb79-46d4-98ef-b230c8015b24)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175259984/a3d617a5-257b-4505-8ae9-4170286c17f9)

**Comment by CrazyWhatzthis** [comment]
Second photo with markings on where it is
![which](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175259984/09cffb5d-a334-4852-9e7a-b0a40767800f)

**Comment by CrazyWhatzthis** [comment]
oops

**Comment by thelilh** [comment]
it's supposed to be partial content, i'll fix it
