### ISSUE TITLE
Belarus is not core

### ISSUE THREAD

**Issue by sagirismet** [kalterkrieg/Kalterkrieg-bug-reports#224]
### OS

Windows 10

### HOI4 Version

1.14.7 

### Kalterkrieg Version

1.1

### List any other mods used

-

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

All except 3 dlc given for free

### Explanation of the Issue

Although the Lithuanian-Belarusian kingdom was established, Belarusian lands are not core.

### Steps to reproduce

Just move the time forward

### Possible Cause

-

### Screenshots

![image](https://github.com/user-attachments/assets/0f6f408f-d7e2-47ff-8cb7-74e0d23dc561)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
This is intentional and is to represent Belarus not fully being integrated into Lithuania as of yet. This may be expanded in future updates.
