### ISSUE TITLE
RUS - Wrong date of birth of Gorgulov

### ISSUE THREAD

**Issue by PozhiloySad** [kalterkrieg/Kalterkrieg-bug-reports#225]
HOI4 version: Latest
Kalterkrieg version: Latest
List any other mods used: No other mods

**Explanation of the issue:**
The wrong date of birth, he can't be here and still be born in the future.

**Screenshots:**
https://i.imgur.com/oRZpsqa.png

**Comment by thelilh** [comment]
Fixed
