### ISSUE TITLE
GER - resume_the_sozialwohnungsbauprogramm_desc

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#226]
### OS

Windows 10

### List any other mods used

Graphic Map Mods only

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/97631678/296b15ac-130d-42d6-9cc3-86550dfc7d63)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Focus descriptions are a low priority item and will be added eventually.
