### ISSUE TITLE
NEE - Harriman election event

### ISSUE THREAD

**Issue by Wolfstorm75** [kalterkrieg/Kalterkrieg-bug-reports#227]
**Quick questions**
HOI4 version:1.14
Kalterkrieg version:0.1.1
List any other mods used: only official submods

In the 1949 Harriman election event it says it's his second term, despite it being only his first. The only thing I can think of that may have thrown it off was completing the redamation of New Jersey and Pennsylvania in the middle of the campaign

![20240711154739_1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/87508501/e6d2af3e-cf45-4657-8d89-469385fe42da)

**Comment by thelilh** [comment]
Fixed, thank you for reporting this
