### ISSUE TITLE
SWI - Haute-Savoie core state

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#228]
**Describe the specific change you would like:** Make that Haute-Savoie is not considered a core state of Switzerland after it transfers it to France.

**Explain the reasoning behind this actionable change:** It is just seems logical? And in gameplay mechanics it can just ruin the relations with France.

**Comment by Kennedy2523** [comment]
It isnt core swiss land, thats why its given over in the first place.
