### ISSUE TITLE
GLOBAL - Head of Government GUI

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#229]
**Describe the specific change you would like:** As i was answered already, HoG GUI eventually wil be for every major country, but also I suggest to make it visible for player when he desires to see what kind of HoG is ruling right now in bot-led Canada for example.

**Explain the reasoning behind this actionable change:** It is just cool, i guess? Also Leaf just told me to send it here.

**Comment by thelilh** [comment]
"it's just cool, i guess" is the best reason. thank you, i will fix this 😄

**Comment by thelilh** [comment]
This has now been implemented and will be available in the next patch
