### ISSUE TITLE
Nation(s) Affected - Summary of Bug

### ISSUE THREAD

**Issue by Texican-BC** [kalterkrieg/Kalterkrieg-bug-reports#23]
### OS

Windows 11

### HOI4 Version

Most Recent

### Kalterkrieg Version

1.0.0

### List any other mods used

None

### Were you using Steam?

yes

### Which expansions do you NOT have?

AAT

### Explanation of the Issue

Can't get assigned or assign

### Possible Cause

Perms? maybe

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
