### ISSUE TITLE
GER - The Bundesrat GUI 

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#232]
### OS

Windows 10

### List any other mods used

Graphic Map Mods only

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Explanation of the Issue

At first it was okay, but some time after the Rhineland thing, it became not fully visible with cities/duchies out of sight.

### Screenshots

![image](https://github.com/user-attachments/assets/3a90eb15-dbe9-49e3-bcdb-f9c483935c49)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
