### ISSUE TITLE
GER - "Accord Exercises in the North Sea" event

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#233]
### OS

Windows 10

### List any other mods used

Graphic Map Mods only

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Explanation of the Issue

The first option misses localisation.

### Screenshots

![image](https://github.com/user-attachments/assets/a85d8515-077e-459e-8560-84d13c44aa59)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
