### ISSUE TITLE
GER - krg_ger.311

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#234]
### OS

Windows 10

### List any other mods used

Graphic Map Mods only

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Explanation of the Issue

Event lacks localisation.

### Screenshots

![image](https://github.com/user-attachments/assets/976346c1-03e1-45c3-84c3-b61f1876cc04)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Added to our loc tracker. Thank you for reporting!

**Comment by thelilh** [comment]
Not a localization issue, we will fix this in other ways. Hence reopening

**Comment by Axolotl3823** [comment]
Has been fixed
