### ISSUE TITLE
GER - Bundesradt GUI

### ISSUE THREAD

**Issue by TheAdrianbbc** [kalterkrieg/Kalterkrieg-bug-reports#235]
### OS

Windows 10

### Were you using Steam?

No

### Were you in multiplayer?

No

### Explanation of the Issue

I Lost Bundesrat GUI after von Papen was kicked by Wilhelm IV

### Screenshots

![image](https://github.com/user-attachments/assets/8dd92f71-bbe0-4708-a265-41cdc54d9024)
![image](https://github.com/user-attachments/assets/edc0a0b8-f214-4c5e-b61c-146dd82486d8)
![image](https://github.com/user-attachments/assets/5221f2e2-4909-4d0d-9676-3e0707539cbd)

### Save File

[GER_1952_05_24_13.zip](https://github.com/user-attachments/files/16197464/GER_1952_05_24_13.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Texican-BC** [comment]
WAD the Reichstag disables when the centralizing act is passed. Adding a missing tooltip and the vote should pass automatically
