### ISSUE TITLE
GLOBAL - Cant use escape key on country selection menu

### ISSUE THREAD

**Issue by CrazyWhatzthis** [kalterkrieg/Kalterkrieg-bug-reports#236]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

The "HOT" key (nuke hotkey mod)

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have them all.

### Explanation of the Issue

When you press escape, the gui dissapears for a split second, and then comes back without going to the menu. It also sets the country you have selected as german empire, even if you had another country like canada selected prior. This isn't a save file issue, so I wont add it.

### Steps to reproduce

Relatively easy, just open the game, press new game, and try to press escape.

### Possible Cause

possibly because nothing is set to happen when you click esc on this menu? I couldn't know though.

### Screenshots

![image](https://github.com/user-attachments/assets/26b2bdd4-a8a8-4da5-8836-ba48082e8172)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16198531/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Sadly, this is a PDX issue and we can't fix it
