### ISSUE TITLE
Russia doesn't have a claim on Slanimas (State ID 95)

### ISSUE THREAD

**Issue by pjlambe78** [kalterkrieg/Kalterkrieg-bug-reports#238]
**Quick questions**
OS:
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used:
Were you using Steam? yes
Were you in multiplayer? no
Which expansions do you NOT have?
i have all expansions
**Explanation of the issue:**

Russia doesn't have a claim on Slanimas (State ID 95)
**Steps to reproduce:**

Click on the state

**Possible cause:**
State not assigned

**Screenshots:**
https://imgur.com/a/KEZkPvf

**Comment by Ymerein** [comment]
Fixed
