### ISSUE TITLE
GLOBAL - "No Elections"

### ISSUE THREAD

**Issue by Mifevra** [kalterkrieg/Kalterkrieg-bug-reports#239]
**Describe the specific change you would like:** Instead of that kind of countries which gets their elections, change the "No Elections" thing to "Elections via Events" or something like that.

**Explain the reasoning behind this actionable change:** It seems unnatural when it says that country got no elections (when it surely got it).

**Comment by Flizzyclone** [comment]
Perhaps a better solution to this is just to be better at setting when elections are in the history file

**Comment by thelilh** [comment]
This suggestion has been approved and added to the game. Thank you for suggesting it.
