### ISSUE TITLE
American Union State Post-War Flag Change

### ISSUE THREAD

**Issue by InsanityGAMER-ihateevan** [kalterkrieg/Kalterkrieg-bug-reports#24]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Used the Offical Kalterkrieg Collection

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None

### Explanation of the Issue

The AUS when choosing to take the United States of America name option does not have it's flag revert back to old glory

### Steps to reproduce

Win the 3ACW as the AUS and revert to the United States

### Possible Cause

My guess is that it could be some issue with one of the other 3D model mods although id not have any clue as to why

### Screenshots

https://i.imgur.com/ZycM2hG.jpg

### Save File

[Ironman American Union State 1.zip](https://github.com/user-attachments/files/16100801/Ironman.American.Union.State.1.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
