### ISSUE TITLE
TEX/CAL/NEE - If NEE capitulates, so does CAL

### ISSUE THREAD

**Issue by glxysz** [kalterkrieg/Kalterkrieg-bug-reports#241]
**Quick questions**
OS:windows
HOI4 version:newest one, 1.14.something
Kalterkrieg version:1.01 i think
List any other mods used:a bunch, but i'm pretty sure they have no correlation with my issue
Were you using Steam? yes
Were you in multiplayer? no
Which expansions do you NOT have? none

**Explanation of the issue:**
the pacific states cap if new england caps

**Steps to reproduce:**

1.fire up the 3ACW

2.have the longists capitulate new england, if pacific doesnt cap, then it might be something to do with me, but i doubt that

**Other info:**

**Possible cause:**
because new england is the faction leader if new england caps, so does the pacific states, so this means that even if the pacific states is in the gates of washington, if new england caps so does pacific states

**Log file:**

**Screenshots / Video:**

**Save game:**

[kalterkrieg bug thing_temp.zip](https://github.com/user-attachments/files/16201150/kalterkrieg.bug.thing_temp.zip)

also the "current wars" thing doesnt work, it just shows the list of events, idk if its something to do with my mods, but if it isn't you prob already know of this lol

**Comment by thelilh** [comment]
the current wars is working as designed, there is a tab for current wars. we should rename the button

**Comment by kandis125** [comment]
Added a Scripted Peace deal for the American Union state annexing each country seperately.

**Comment by kandis125** [comment]
Added a Scripted Peace deal for the American Union state annexing each country seperately.
