### ISSUE TITLE
GER - Mitteleuropa focuses give extreme effects that don't match the descriptions

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#242]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

N/A

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Alliegence

### Explanation of the Issue

1. The "Create the Europa Verteidigungstruppe" focus is supposed to give +5% recruitable population factor and +5% coordination. Instead it gives +50% for both.
2. The "Found the Europacouncil" focus is supposed to give -0.05 daily political power. Instead it gives -0.50 daily political power.
3. the "Combined European Chiefs of Staff" focuses is supposed to give +0.03 army experience gain and +10% coordination. Instead it gives +0.30 army experience and +100% coordination.

Sidenote: the other Mitteuropa focuses might also have problems like this and should probably be checked too.

### Steps to reproduce

1. Go through the Mitteleuropa focuses (or just focus.nochecks + focus.autocomplete)
2. Look at what effects the focuses have and compare it to the Mitteleuropa national spirit

### Possible Cause

oversight

### Screenshots

![Screenshot 2024-07-13 163831](https://github.com/user-attachments/assets/70540243-b99a-4147-a442-d464bd2f0de5)
![Screenshot 2024-07-13 163912](https://github.com/user-attachments/assets/df74dca0-8363-4c96-8ef4-f42bc6c7d21c)
![Screenshot 2024-07-13 164025](https://github.com/user-attachments/assets/48ea560b-a4e6-43e2-b034-3f48763c0e19)
![Screenshot 2024-07-13 164050](https://github.com/user-attachments/assets/45d074d3-d1a6-4365-ae6b-f9281c4e435f)

### Save File

N/A

### Log Files

N/A

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
