### ISSUE TITLE
CHI - 'Rural surrounds Urban' national spirit has no unique GFX icon

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#243]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/c76d34f8-67be-439a-8c7a-a6d800757038)

### Save File

[CHI.zip](https://github.com/user-attachments/files/16209567/CHI.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Fixed
