### ISSUE TITLE
CHI - "surrounds" is not capitalize with the first letter "s" 

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#244]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: Kalterkrieg Models and All Kaiserreich Models

**Explanation of the issue:**
It should be 'Rural Surrounds Urban'.

**Screenshots:**
![Image_1](https://github.com/user-attachments/assets/7c90ce47-fbd6-443e-b0f7-da5f99353fb2)

**Comment by kandis125** [comment]
Fixed this and other national spirit spelling errors
