### ISSUE TITLE
TEX - A "almostas" typo in Electoral Introduction event

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#251]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: Kalterkrieg Models and All Kaiserreich Models

**Explanation of the issue:**
The words "almost" and "as" are not separate or have no space between them. It should be "almost as" words.

**Screenshots:**
![Image_1](https://github.com/user-attachments/assets/2d7b78ec-2fbc-406f-b55d-97feecf84af1)

**Comment by kandis125** [comment]
fixed
