### ISSUE TITLE
GER - The content of national populist path cant continue past the New State reforms 

### ISSUE THREAD

**Issue by Jelosus2** [kalterkrieg/Kalterkrieg-bug-reports#252]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

latest in Steam

### List any other mods used

No other mod

### Were you using Steam?

No

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have all

### Explanation of the Issue

cant continue the focus tree

### Steps to reproduce

Play normally the national populist path, you cant pass "Bredows Vision Holds" or the "Politicise the Militarists" focuses

### Possible Cause

Error in the focus

### Screenshots

![image](https://github.com/user-attachments/assets/e7a5920f-0d71-4d33-9ebc-9d8144be2324)

### Save File

[autosave.zip](https://github.com/user-attachments/files/16262826/autosave.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16262876/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
There isn't a national populist path and this is very imprecise, who is your chancellor?

**Comment by Axolotl3823** [comment]
Not enough context, did not respond. And this has probably been fixed now
