### ISSUE TITLE
Global - Long event title overlaps with the line dots

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#253]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: Kalterkrieg Models and All Kaiserreich Models

**Explanation of the issue:**
I saw the event title overlaps with the line dots in some events.

**Screenshots:**
![Image_1](https://github.com/user-attachments/assets/0c6a6a56-ee39-4c10-ade0-ba48cc732038)

![Image_2](https://github.com/user-attachments/assets/d737f771-773b-4a59-ae01-67cd07f475a3)

**Comment by kandis125** [comment]
fixed
