### ISSUE TITLE
TEX - 'A New America' focus description is not done

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#254]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Explanation of the Issue

I know the American Union State(TEX) is not yet done to become fully content, but I report it for a reminder.  

### Screenshots

![Image_1](https://github.com/user-attachments/assets/baf44b41-60f3-4667-9459-25018b2afccd)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Focus descriptions are a very low priority item for us and will be added in due time.
