### ISSUE TITLE
TEX - Command Power doesn't decrease when selecting 'Crack Down on Insurgency Supporters' decision

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#256]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.1

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Screenshots

![Image_1](https://github.com/user-attachments/assets/e002b827-7943-450b-ad10-76c535cdb6d2)

![Image_2](https://github.com/user-attachments/assets/422df0b6-4e3c-4634-8eca-132085906c50)

### Save File

[TEX_play.zip](https://github.com/user-attachments/files/16265002/TEX_play.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
