### ISSUE TITLE
RUS - no claims on certain regions

### ISSUE THREAD

**Issue by dimitrovnovikov** [kalterkrieg/Kalterkrieg-bug-reports#259]
### OS

Windows 10

### HOI4 Version

newest

### Kalterkrieg Version

newest

### List any other mods used

none

### Were you using Steam?

No

### Were you in multiplayer?

No

### Which expansions do you NOT have?

i have all

### Explanation of the Issue

no russian claims on dnipropetrovsk in ukraine, and in slanimas in poland

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
Both of these are fixed internally
