### ISSUE TITLE
CAL - 'Implement the National Security Act' focus has no appear effects to give

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#261]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/be9c3092-abd5-4b69-8b55-85f69a7a6a55)

### Save File

[CAL_play.zip](https://github.com/user-attachments/files/16283548/CAL_play.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
We are currently working on fixing the Pacific States of America and we are closing this story as a result.
