### ISSUE TITLE
CAL - A slight space before "As" in the second paragraph from the 'Hughes Inauguration' event

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#262]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: Kalterkrieg Models and All Kaiserreich Models

**Explanation of the issue:**
_No Response_

**Screenshots:**
![Image_1](https://github.com/user-attachments/assets/c266e6d5-fe01-4c93-8c85-c74bca4aaef1)

**Comment by kandis125** [comment]
fixed
