### ISSUE TITLE
Accord/Reichpakt - Event for being able to send volunteers to proxy wars

### ISSUE THREAD

**Issue by GratePaddle** [kalterkrieg/Kalterkrieg-bug-reports#263]
<details>
<summary>Please Note (click to expand)</summary>
Suggestions that don't match this template will be closed. We understand this can seem harsh, but in order to ensure we are able to keep on track of bugs other serious issues it is vital our issue tracker is kept organised. The kinds of suggestions that will get close and directed elsewhere include, but are not limited to:
- Anything that suggests adding new content
- Anything that is focused around changing lore
- Anything that will take a significant amount of time to implement
- Anything that isn't specific and actionable change about existing content, as the template specifies
Please know that this isn't out of any disrespect for the ideas you might have for the mod, and encourage people with a passion to get involved either on the subreddit, the discord or even via joining the team itself. But that being said, suggestions that don't match this template will be closed.
</details>

**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.2

**Describe the specific change you would like:**
An event notifying members of the Accord/Reichpakt (as well as aligned nations, i.e. the AUS) of their ability to send volunteer divisions in proxy wars, such as the Chinese Civil War or Congo War.

**Explain the reasoning behind this actionable change:**
As you cannot send volunteers on day one of the conflict, I often find myself getting distracted with other stuff, only to realize later that the proxy war has already ended in a result unfavorable to me. A notification in the form of an event that would trigger after the Accord Council deliberates, or after Germany/AUS can send volunteers (which, in my experience, appears to randomly trigger after some time without any external trigger) would fix this problem.

**Additional context or comments:**

**Comment by Kennedy2523** [comment]
Added, thanks for the suggestion!
