### ISSUE TITLE
In-Game Crash After Unpausing The Game

### ISSUE THREAD

**Issue by IvanSerovTNO** [kalterkrieg/Kalterkrieg-bug-reports#265]
**Quick questions**
OS: Windows 11 x86_64
HOI4 version: 1.14.7.f4d3
Kalterkrieg version: 0.1.2
List any other mods used: Kalterkrieg Models - Kaiserreich Models Compatibility Submod, Kaiserreich Models - Base Game, Kaiserreich Models - Death or Dishonor DLC, Kaiserreich Models - Together for Victory DLC, Kaiserreich Models - Waking the Tiger DLC, Kaiserreich Music
Were you using Steam? Yes
Were you in multiplayer? No
Checksum (four-letter code at the bottom of your title menu): f03b
Which expansions do you NOT have?
Allied Armor, Arms Against Tyranny, Axis Armor, Battle For The Bosporus, By Blood Alone, Eastern Front Planes, La Resistance, Man The Guns, No Step Back, Trial of Allegiance, 
**Explanation of the issue:**
Whenever I try to load a save game and unpause the game, the next hour on the same date will crash. The same thing happens when I tried to load an older Kalterkrieg save game.

**Steps to reproduce:**

1. Load the save game.

2. Unpause the game.

**Log file:**

[error.log](https://github.com/user-attachments/files/16289636/error.log)
[system.log](https://github.com/user-attachments/files/16289637/system.log)

**Save game:**
[autosave.zip](https://github.com/user-attachments/files/16289635/autosave.zip)

**Comment by Axolotl3823** [comment]
Presumably this is caused by trying to load an old save game from the previous version. When did you make this save?

**Comment by IvanSerovTNO** [comment]
I saved it today, but after the Kalterkrieg update I think. If this is
because of the update, is there an update in the fututee to fix this?

**Comment by IvanSerovTNO** [comment]
Im sorry, it was before the update, not after the update.

**Comment by MrCovenant000** [comment]
We have made fixes that make it save game incompatible so there is nothing we can do
