### ISSUE TITLE
NEE - Republican gaining support in the wrong evet

### ISSUE THREAD

**Issue by IknowSHall** [kalterkrieg/Kalterkrieg-bug-reports#266]
### OS

Windows 10

### HOI4 Version

Latest

### Kalterkrieg Version

Latest

### List any other mods used

None

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None

### Explanation of the Issue

When the event localisation displays that the democrats have gained in the polls for new england (after Harriman has been elected), the republicans gain support rather than the democracts

### Steps to reproduce

I'm not sure if it happened prior to Harriman's election but I only noticed it after

### Possible Cause

Mixed up effects probs

### Screenshots

![image](https://github.com/user-attachments/assets/8e4f0cb0-ab1b-4eda-a1a8-ff3143d695f6)

### Save File

-@ me on discord at @Iknowshall, but this is a relatively simple issue, so I doubt you need it - lmk if otherwise

### Log Files

-@ me on discord at @Iknowshall, but this is a relatively simple issue, so I doubt you need it - lmk if otherwise

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by IknowSHall** [comment]
Now that I think about it, I did choose the play the republicans then lost as they republicans which may be causing this bug - and btw all generic events where democrat support should increase, increase republican support instead

**Comment by IknowSHall** [comment]
Odly, the following event works:
![image](https://github.com/user-attachments/assets/0d515b58-05f1-471c-9532-43f6e1cf052b)

**Comment by thelilh** [comment]
Fixed
