### ISSUE TITLE
NEE-massive spending on oil in game start

### ISSUE THREAD

**Issue by frontierplay** [kalterkrieg/Kalterkrieg-bug-reports#267]
### OS

Windows 10

### HOI4 Version

current

### Kalterkrieg Version

current

### List any other mods used

official radio

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Explanation of the Issue

by the start of the game, the fuel draining to zero, and no matter what you do, trading, building refineries, or even deleting units I still end up going to zero and the repeating use of the fuel crises leading to NEE having its stability become -100% by 1954,

### Steps to reproduce

start the game as NEEStart

### Possible Cause

either the Units using way too much or the buildings using fuel.

### Screenshots

![image](https://github.com/user-attachments/assets/8503cae0-cd3d-46ca-993c-2644cf07b531)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
