### ISSUE TITLE
TEX - TEX_CCC_payments national spirit is not localized

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#268]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/78777ff7-5d78-4aab-96fd-a4dd8b22b80e)

### Save File

[CAL_play.zip](https://github.com/user-attachments/files/16310225/CAL_play.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Fixed
