### ISSUE TITLE
UKR - Wrong airzone name

### ISSUE THREAD

**Issue by BeneKyrill** [kalterkrieg/Kalterkrieg-bug-reports#269]
**Quick questions**
OS:
HOI4 version: Newest
Kalterkrieg version: 0.1.2
List any other mods used: FPS Map
Were you using Steam? Yes
Were you in multiplayer? No
Which expansions do you NOT have? i have all expansions

**Explanation of the issue:**
Eastern Ukrainian Airzone is called South West China

**Steps to reproduce:**

1. Open Airzone Map

**Screenshots:**
![Screenshot 2024-07-19 152645](https://github.com/user-attachments/assets/8000d478-6756-46d6-ad62-e2d8b73e730f)

**Comment by kandis125** [comment]
Try updating the mod, I tried recreating the problem, in the base mod and with FPS map yet it still says Eastern Ukraine

**Comment by BeneKyrill** [comment]
thanks for the reply, i now know myself why this happened, i overlooked that i still had the great war redux mod active, surprising that the game didn't crash.
