### ISSUE TITLE
DNF - can't choose some focuses due to leader name translation

### ISSUE THREAD

**Issue by KingElessar** [kalterkrieg/Kalterkrieg-bug-reports#270]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Korean Translation (https://steamcommunity.com/sharedfiles/filedetails/?id=3282337456)

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

none

### Explanation of the Issue

Hello, I'm King_Elessar, a Korean translation modmaker for Kalterkrieg.

I'm contacting you because I'm currently experiencing an issue where when I try to apply a translation mod for non-alphabetic languages, including Hangul, Hanji, and Kana, and select a focus that requires a figure such as Boris Savinkov or Wilhelm IV to be a leader, this is not possible due to lack of prerequisites.

### Possible Cause

This is an issue with translating people's names, and the Korean translation team I'm part of has encountered the same issue with the Darkest Hour mod. The direct cause of the issue we identified was due to putting people's names as strings rather than blocked character IDs, and there is a workaround for this on the HOI4 wiki.

(https://hoi4.paradoxwikis.com/Character_modding)

### Screenshots

![1721403211](https://github.com/user-attachments/assets/3614071c-de3d-4280-a3a0-878574655090)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Thanks for pointing this out to us, we are working on making sure leader names are strings and they will be implemented slowly. Reach out to me on discord and we can give you access to our translator channel.

**Comment by thelilh** [comment]
Will be fixed in next patch
