### ISSUE TITLE
NEE - Delaying the integration of New Jersey and Philadelphia does not give a penalty

### ISSUE THREAD

**Issue by Maxty0** [kalterkrieg/Kalterkrieg-bug-reports#272]
### OS

Windows 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

FPS Map (no coloured icons and strategic view adjustments); Better Mechanics : Optimization

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Allegiance, Arms against Tyranny, By Blood Alone, No Step back, Battle for the Bosporus, La Resistance, Man the Guns, 

### Explanation of the Issue

The NEE focus tree indicates that you will incur a penalty if you don't complete both the "Creating the Next generation" and "Ending Martial Law" focuses by the time that the election season begins.

But, the election proceeds without penalty and you can delay the integration of the states forever if you don't complete both focuses.

![image](https://github.com/user-attachments/assets/60078eca-b2bd-4ce6-85cc-c71272f49b0e)

![image](https://github.com/user-attachments/assets/67aa6623-8099-41f0-8133-30e37d76ed48)

As you can see, in 1950 while neither the focuses are completed nor the states integrated. No penalty was ever received against Harriman or former president Baldwin.

### Steps to reproduce

1.- Play as NEE
2.- Don't complete both "Creating the Next generation" and "Ending Martial Law" focuses
3.- Play until Election season 1949 if you want to see that a penalty does not occur.
4.- (Optional) Keep playing forever and NJ and Philadelphia will never be integrated unless you do the focuses

### Possible Cause

The cause of this might the error in this "limit" in event nee.13

![image](https://github.com/user-attachments/assets/650a0b24-b0b6-4deb-95e4-869e99ee7b61)

There are two mistakes there. The first one is that "has_country_flag = NEE_completed_NEE_creatingnextgen." has a misplaced dot at the end, which is causing for the flag to never be read. The second mistake would be the logic behind it. If it worked as designed, then the occupation would FAIL if both focuses were COMPLETED.

The solution would be to remove the misplaced dot and to rewrite the limit as:

limit = {
				NOT = {
					AND = {
						has_country_flag = NEE_completed_NEE_creatingnextgen
						has_country_flag = NEE_completed_NEE_endingmartiallaw
					}
				}
			}

![image](https://github.com/user-attachments/assets/33d88e3c-fd1b-452b-b37e-c7def0439759)

Applying this fix triggers the correct event after the election season begins, even if you have not completed the focuses. This next image is the event triggered when the fix is applied.

![image](https://github.com/user-attachments/assets/f519d0b1-79ee-4a41-ad24-9f3e4a54ca35)

I hope this helps. Cheers!

### Screenshots

![image](https://github.com/user-attachments/assets/60078eca-b2bd-4ce6-85cc-c71272f49b0e)

![image](https://github.com/user-attachments/assets/67aa6623-8099-41f0-8133-30e37d76ed48)

![image](https://github.com/user-attachments/assets/8b1019bc-457a-444a-8c45-655325d87419)

### Save File

[NEE_1949_12_30_23.zip](https://github.com/user-attachments/files/16321514/NEE_1949_12_30_23.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16321518/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Very helpful! Thank you for spotting the bug and showing the fix. If you are interested, please apply to the team, we could use folks like you to help improve the mod. Send in an application on discord and shoot me a DM once you do.
