### ISSUE TITLE
CAL - Election Season decision still appeared despite the election is finish

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#273]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/1a806f28-f3c6-4a8d-b094-53604c7ba713)

![Image_2](https://github.com/user-attachments/assets/bc7524f9-dbbb-4b8c-986e-f25cd708d9c4)

### Save File

[CAL_play.zip](https://github.com/user-attachments/files/16322594/CAL_play.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
Seems like an easy fix to the visible trigger for the decision category:
Go from `has_country_flag = CAL_Able_To_See_Campaign`
to
```
has_country_flag = CAL_Campaign_Season_Unlock
NOT = {
	has_country_flag = CAL_Election_Over
}
```
like the electoral explanation decision uses.
The `CAL_Able_To_See_Campaign` is used no where else and can thus be removed.

**Comment by MrCovenant000** [comment]
This should be adjusted in the next patch
