### ISSUE TITLE
CAL - The Pacific States Congress decision status bugs

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#276]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Explanation of the Issue

- [ ] After selecting The Pacific Agriculture Act decision, the status of the selected bill is still showing "No Bill" sign, no bill description and no bill effects about the selected bill despite The Pacific Agriculture Act has been selected. 

- [ ] After selecting the 'House of Representatives and Senate of selected bill' decisions due to the majority is approving the bill, the status of the 'House of Representatives and Senate' are marked "No Bill is Before This Chamber" instead of marking "The Bill Passed" or something like this. Once the bill voting done, the status should be marked "No Bill is Before This Chamber" again. This bug is affecting to all CAL's bills.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/198984a4-0740-4c32-94f2-9f5fb0c5d76e)

![Image_2](https://github.com/user-attachments/assets/64b68929-58bc-4952-87a9-c0eab0cd2fed)

### Save File

[CAL_play.zip](https://github.com/user-attachments/files/16322670/CAL_play.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
We are currently working on fixing the Pacific States of America and we are closing this story as a result.
