### ISSUE TITLE
GER - Wilhelmshaven Naval Base in the wrong location

### ISSUE THREAD

**Issue by Ballooney** [kalterkrieg/Kalterkrieg-bug-reports#28]
**Quick questions**
OS: Windows 11
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: N/A
Were you using Steam? Yes
Were you in multiplayer? No
Which expansions do you NOT have? Trial of Allegiance

**Explanation of the issue:**
The naval base at Wilhelmshaven is located at the Heligoland islands instead of Wilhelmshaven itself, like it is in both Kaiserreich and historically

**Possible cause:**
Oversight

**Screenshots:**
![Screenshot 2024-07-04 082830](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/115955214/a7387dd6-6fa8-4905-9a72-1e0431120c41)

**Comment by Kennedy2523** [comment]
Fixed.
