### ISSUE TITLE
CAL - No voted on for The McCarran Internal Security Act and The Morse Domestic Affairs Act in the Congress decision texts

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#283]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Explanation of the Issue

After selecting The McCarran Internal Security Act or The Morse Domestic Affairs Act decision, the status of the bill is still showing "No Bill" sign, no bill description and no bill effects about the selected bill despite The McCarran Internal Security Act or The Morse Domestic Affairs Act has been selected.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/00d49c6e-a35a-4b3a-a261-6593ee11e71e)

### Save File

[autosave.zip](https://github.com/user-attachments/files/16324047/autosave.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
CAL is WIP

**Comment by thelilh** [comment]
We are currently working on fixing the Pacific States of America and we are closing this story as a result.
