### ISSUE TITLE
MAF - An extra "S" in the Union of South Africa Moves Into Northern Rhodesia Event

### ISSUE THREAD

**Issue by IvanSerovTNO** [kalterkrieg/Kalterkrieg-bug-reports#288]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.2
List any other mods used: Kalterkrieg Models, Kaiserreich Models, and Kaiserreich Music

**Explanation of the issue:**
It says "Union of South Africa Moves Into Northern RhodesiaS" in the title. It have an extra "S" at the end of Rhodesia.

**Screenshots:**
![20240724201524_1](https://github.com/user-attachments/assets/6a1f7638-b800-433d-aa30-cb5f7a40ae13)

**Comment by thelilh** [comment]
Fixed
