### ISSUE TITLE
DNF - Conservative party name change

### ISSUE THREAD

**Issue by sayko06** [kalterkrieg/Kalterkrieg-bug-reports#289]
I'm not sure how it happens, but Danubia's conservative parties can name change from CSP-OKgFP(F/H) to DVP (F/H). The name changes on the political pie chart, but underneath "The Chamber of Deputies" it keeps the old name. 

**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.2

**Describe the specific change you would like:**
When/if the conservative parties have a name change, the name underneath the chamber of deputies should change aswell.

**Explain the reasoning behind this actionable change:**
It's just a nice detail to add if possible

**Additional context or comments:**
I was unsure if it was a bug or not so I just put it here

![suggestion2](https://github.com/user-attachments/assets/e463b1c5-95fb-4946-8202-bfa3939345b2)
![suggestion1](https://github.com/user-attachments/assets/133db7b6-2231-4d47-8dde-c5e9f6367b47)

**Comment by thelilh** [comment]
not a suggestion, this is a bug

**Comment by thelilh** [comment]
this has now been fixed :)
