### ISSUE TITLE
PSA, NEE, AUS - Broken doctrine bonuses

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#29]
### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/67cd56b4-ae11-4725-9a3f-e24fce1e4bda)
These are the broken focuses for the AUS tree.
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/6c124d29-de21-4142-bd52-8a1386f35467)
This is for the PSA tree.
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/3dcd7504-e8bb-4518-af2e-59567c8afcf7)
This is the broken focus for the NEE tree.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
