### ISSUE TITLE
CAN - Unable to Build Synthetic Rubber Refineries

### ISSUE THREAD

**Issue by bijon1111** [kalterkrieg/Kalterkrieg-bug-reports#298]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7f4d3 (f03b)

### Kalterkrieg Version

kalterkrieg_012

### List any other mods used

- FPS Map Mod
- Division Limiter Extender 
- More Building slots
- Better Mechanics : Training and Experience
- Lower Tank Build Cost
- Lower Build Cost (Land)
- Lower Build Cost (Air)
- Lower Build Cost (Naval)
- Lower Build Cost (Buildings)
- Lower Artillery Build Cost
- Lower Infantry Equipment Build Cost
- All Unit Types Allowed
- Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A (I have all of them)

### Explanation of the Issue

Unable to build synthetic rubber refineries as the option does not appear in the Construction Menu, even with Synthetic rubber research unlocked.

### Steps to reproduce

Simply playing Canada in the mod.

### Possible Cause

Undetermined

### Screenshots

![rubberbug](https://github.com/user-attachments/assets/6cf55afd-0e06-4ee2-92ac-5199874fe27b)

### Save File

[CAN_1950_08_13_09 - Copy.zip](https://github.com/user-attachments/files/16385341/CAN_1950_08_13_09.-.Copy.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
I'm sorry, what's the bug?

**Comment by bijon1111** [comment]
For some reason, when I tried to edit my issue I had open since yesterday, it just randomly posted it. Apologies. I was still filling out info

**Comment by Ikidikid** [comment]
I think your other submods are causing this issue. Try to disable all submods except Kalterkrieg Models and All Kaiserreich Models submods to see if there is no bug.

**Comment by bijon1111** [comment]
> I think your other submods are causing this issue. Try to disable all submods except Kalterkrieg Models and All Kaiserreich Models submods to see if there is no bug.

I’ve identified the More Building Slots mod as the culprit. Initially, I didn't suspect my submods because none of them seemed related to or should affect the construction tab. However, I was mistaken. Interestingly, I haven't encountered this issue with other main mods in my experience. Honestly a partially embarrassing situation for me, lol. This issue can be closed.
