### ISSUE TITLE
TUR - Replace Low Resolution Spirit Icon

### ISSUE THREAD

**Issue by ari33333** [kalterkrieg/Kalterkrieg-bug-reports#3]
**Quick questions**
HOI4 version: other user's screenshot
Kalterkrieg version: 0.1

**Describe the specific change you would like:**
Replace the Turkish spirit icon circled in the screenshot.

**Explain the reasoning behind this actionable change:**
This icon is very low-resolution and was removed from KR last week for that reason. 

**Additional context or comments:**
![IMG_5293](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/173859732/28e4eb9a-e942-4f65-b2f0-c4b75e8fd55a)
Issue that got the icon removed from KR: https://github.com/Kaiserreich/Kaiserreich-4-Bug-Reports/issues/24770

**Comment by Kennedy2523** [comment]
This isnt an issue we are going to look into for now, we will upgrade our GFX eventually, but for now this is up to our standards. Thanks for playing!
