### ISSUE TITLE
UOB - End of the Birmingham Trials news event fired despite UOB existing

### ISSUE THREAD

**Issue by remington1218** [kalterkrieg/Kalterkrieg-bug-reports#30]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

None

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None

### Explanation of the Issue

End of the Birmingham Trials news event fired despite UOB existing

### Steps to reproduce

Win the revolution as UOB

### Possible Cause

I would assume its because the UOB winning the revolution isnt accounted for in this event

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/97780043/72bd872e-73e4-499d-ad4b-eae52dc3e2db)

### Save File

[UOB_1949_02_25_13.zip](https://github.com/user-attachments/files/16100971/UOB_1949_02_25_13.zip)
This is 1 day before the event fires

### Log Files

[logs.zip](https://github.com/user-attachments/files/16100973/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
