### ISSUE TITLE
GER - "e" is not capitalize letter of the beginning letter of the word "expires!" 

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#305]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1.1
List any other mods used: Kalterkrieg Models and All Kaiserreich Models

**Explanation of the issue:**
It should be "Expires!". 

**Screenshots:**
![Image_1](https://github.com/user-attachments/assets/36e4b549-1bf8-42ef-b380-5509d174a669)

**Comment by thelilh** [comment]
Will be fixed in next patch
