### ISSUE TITLE
Global - Moroccan Revolution Crushed gives 0 point to The Pakt

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#306]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Explanation of the Issue

The Moroccan Revolution Crushed should be given more than 0 points to The Pakt.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/679da22e-982b-4223-b73e-15124e74f342)

### Save File

[autosave.zip](https://github.com/user-attachments/files/16397594/autosave.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
This will be fixed in the next patch
