### ISSUE TITLE
MOR/AMR - There is a strange text in the state details of Sahara state

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#307]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/1e1a886b-31c9-4624-afc8-c3fb5654534f)

### Save File

[autosave.zip](https://github.com/user-attachments/files/16397662/autosave.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
It's part of the state name and it's simply too long. So this is technically working as designed, but I've done some changes to the UI and these will be in the next patch
