### ISSUE TITLE
 In-game Crash while game initialization

### ISSUE THREAD

**Issue by cycak1** [kalterkrieg/Kalterkrieg-bug-reports#31]
**Quick questions**
OS: Windows 11
HOI4 version: 1.14.5
Kalterkrieg version: the latest one
List any other mods used: none
Were you using Steam?: No
Were you in multiplayer? No
Checksum (four-letter code at the bottom of your title menu): d40a
Which expansions do you NOT have? i have all of them

**Explanation of the issue:**
game crashes during *Initializing game*, it happens every time i try to start the mod

**Log file:**
[game.log](https://github.com/user-attachments/files/16101207/game.log)
cant provide the error log since it's over the maximum 25MB limit

**Screenshots / Video:**
![crashmoment](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171765307/0760d6e3-38e9-43d2-9427-50114725a011)

**Save game:**
Attach a save from before the crash, ideally one where it always happens. A save file is necessary to be able to fix CTDs. Issues without saves will be closed.

**Comment by Flizzyclone** [comment]
Do you have the mod from Paradox mods?

**Comment by cycak1** [comment]
> you

yes.

**Comment by cycak1** [comment]
> Do you have the mod from Paradox mods?

yes.

**Comment by Flizzyclone** [comment]
Please try with the hotfix we put out.

**Comment by cycak1** [comment]
> Please try with the hotfix we put out.

just tried it - still, same crash at game initialization
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171765307/b0eff2d8-6dfd-49b7-ab5c-ab42d92c39ca)
i can send you the error log on discord since i cant send it here

**Comment by Flizzyclone** [comment]
this was user error
