### ISSUE TITLE
GER - The State of Katanga Requests Military Assistance event has the same option choice text

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#310]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/56eaa670-d5d3-44b8-b994-f3c0eff92b80)

### Save File

[GER_play.zip](https://github.com/user-attachments/files/16397910/GER_play.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
This and the typo of military is now fixed.
