### ISSUE TITLE
GER - The Kaiser's Funeral event gives Wilhelm III to retire but Wilhelm III is already gone through the Kaiser is Dead event

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#311]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/3f5a01b5-29a0-4bb0-85b1-d13ae6a52a27)

![Image_2](https://github.com/user-attachments/assets/c037c1af-8dfb-4eeb-abb1-8fe62df90b7b)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
This will be fixed in the next patch
