### ISSUE TITLE
GER - Modern Carrier Aircraft national focus gives research bonus for Naval Aircraft instead of Carrier Models

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#314]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Explanation of the Issue

The Modern Carrier Aircraft national focus gives research bonus for Naval Aircraft instead of giving research bonus for Carrier Models, and there are no Naval Aircraft in the Aircraft Research.

### Screenshots

![Image_1](https://github.com/user-attachments/assets/a29cb230-60c8-49fd-91a2-163c99bdbadb)

![Image_2](https://github.com/user-attachments/assets/6ae6f704-1b15-4673-a6f1-aa6c1d5d61c5)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Effect was correct, updated localization to be more accurate.
