### ISSUE TITLE
FRA, NFA, SWI - Cores not granted correctly to Haute-Savoie

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#32]
### Explanation of the Issue

Switzerland has a choice of giving Haute-Savoie to either NFA or FRA, but giving it does not give cores for France or remove cores from Switzerland.
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/24858e27-797a-4fa3-a208-88c0ea100f6e)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
