### ISSUE TITLE
Deutsche Mittelafrika - 2 collapses?

### ISSUE THREAD

**Issue by CrazyWhatzthis** [kalterkrieg/Kalterkrieg-bug-reports#320]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

The "HOT" key (nuke hotkey mod)

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have them all.

### Explanation of the Issue

I was playing as danubia, and when I looked at africa, Deutsche-Mittelafrika got couped, then later, when I looked back at africa, it collapsed, but there are two different balance of power events related to this.

### Steps to reproduce

Get the AAPM to be victorious in deutsche-mittelafrika, then watch as it burns to the ground.

### Possible Cause

No check for a collapse happening once.

### Screenshots

![image](https://github.com/user-attachments/assets/50103582-bf4a-48db-907d-95d2068bb59f)

### Save File

[DNF_1952_05_20_01.zip](https://github.com/user-attachments/files/16420737/DNF_1952_05_20_01.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16420743/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Fixed. Will be added in next patch
