### ISSUE TITLE
GER/ENG - Oxford Conference Does Not End

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#322]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.2

### List any other mods used

TWR Music

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

This may have been brought up already and completed, but for the Oxford Conference, if the UK continually refuses German demands and Germany issues the ultimatum, if the UK ignores it the Conference will not end, so neither will the occupation.

### Steps to reproduce

1 Play as the UK
2 When the Oxford Conference starts keep denying and rejecting Germany's demands
3 Hope RNG works out and France and Canada back you up 
4 Ignore the German ultimatum in (Germany Issues an Ultimatum)
5 The Conference should end in 10 days. Even after a month it does not. 

### Possible Cause

I believe it is because the event Germany gets for the UK ignoring the ultimatum, krg_eng.131, does not have in its option effects a path for ENG to get the event the option gives, so Germany gets it. But that event which ends the Conference, krg_eng.127, is triggered only for the UK. 

### Screenshots

![KRG Git Issue](https://github.com/user-attachments/assets/5297ecef-68ce-4130-bb06-fcc51ee6175e)
Here you'll find what I think is the issue, and another event to compare to which gives the same outcome (both events originating from Germany).

### Save File

[Conference GER Ultimatum.zip](https://github.com/user-attachments/files/16425519/Conference.GER.Ultimatum.zip)
The first one is a save with the event open where the UK can ignore the ultimatum.
[Conference GER Ultimatum AFTER.zip](https://github.com/user-attachments/files/16425532/Conference.GER.Ultimatum.AFTER.zip)
The second is over a month later, showing no changes even after the conference is supposed to end.

### Log Files

[game.log](https://github.com/user-attachments/files/16425540/game.log)
[error.log](https://github.com/user-attachments/files/16425541/error.log)

It's odd though, you can see the event which says Canada supported the UK:
[05:07:32][1948.04.07.01][effectbase.cpp:1691]:  1:00, 7 April, 1948: United Kingdom: krg_can.93
But both the follow up event Germany gets to issue the ultimatum (krg_eng.129) and the event the UK gets where it can ignore it, which is right at the start of the save (krg_eng.131) are not in the game log.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Thanks Yularen, fixed
