### ISSUE TITLE
Text Missing in France

### ISSUE THREAD

**Issue by sagirismet** [kalterkrieg/Kalterkrieg-bug-reports#323]
### OS

Windows 10

### HOI4 Version

1.14.7 

### Kalterkrieg Version

1.3

### List any other mods used

---

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

All except 3 dlc given for free

### Explanation of the Issue

An event has arrived, but it has no text.

### Steps to reproduce

Become Northern France and advance the game by 3 days

### Possible Cause

I don't know

### Screenshots

![image](https://github.com/user-attachments/assets/7e0aa1fd-b24b-482e-bad3-5a22111b0667)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
did you start your game as them or switch after the game started

**Comment by sagirismet** [comment]
I started with Germany, then went straight to France without advancing time and doing nothing.

**Comment by Axolotl3823** [comment]
As expected, that event is only for AI and will only show up if North France was AI, it sets up their AI path allowing them to have a plan
