### ISSUE TITLE
UOB - Start with Exiled Divisions

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#325]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

TWR Music Mod

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

When the Second British Revolution occurs, the UOB tag gets two units which spawn in the Great Lakes Government.

### Steps to reproduce

1: Keep getting Syndicalist Tensions higher and higher

2: Eventually you'll get the timed mission, Suspicious Resistance Movements

3: Do NOT lower Syndicalist Tensions or the mission may complete. Let it time out and the Second British Revolution will occur, with either option (stay as ENG or switch to the UOB) loading in the UOB OOB.

Or just load the save below, pick either option and look at Minnesota.

### Possible Cause

The two units currently use a province for the Great Lakes Government, in the state of Minnesota: 13246, found in the History -> Units -> UOB_Revolution file. 

I think maybe it was supposed to be province 13262 (which is in Lancashire, north of Liverpool). 

I don't know if it matters, but there is in the files with the same province ID a victory point called Southampton. Assuming it's used for ENG, there is no VP where Southampton is on the Channel. Shown in the image below.

### Screenshots

![UoB Exiled Divisions](https://github.com/user-attachments/assets/c78af844-7b8f-4dbf-9073-1bb91d2e5009)

### Save File

[Start Brit Rev.zip](https://github.com/user-attachments/files/16467184/Start.Brit.Rev.zip)

### Log Files

[game.log](https://github.com/user-attachments/files/16467186/game.log)
[error.log](https://github.com/user-attachments/files/16467187/error.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Thank you, fixed
