### ISSUE TITLE
UOB - Incorrect Scope Used

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#326]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

TWR Music Mod

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

If the UOB manages to win it's rebellion against ENG (the Second British Revolution), a follow up event from Germany uses the wrong scope and gives the wrong idea icon for the Treaty of Oxford. But a very minor detail given it is only cosmetic.

### Steps to reproduce

1: Keep getting Syndicalist Tensions higher and higher

2: Eventually you'll get the timed mission, Suspicious Resistance Movements

3: Do NOT lower Syndicalist Tensions or the mission may complete. Let it time out and the Second British Revolution will occur.

4. Win the Revolution within two months so you don't have to fight the Accord. If you go to war with them, hold out a month and the event about the Treaty should spawn.

Or just load the save below. The event in question will trigger on startup.

### Possible Cause

The scope for getting the Oxford Treaty Dynamic Modifier in the event krg_uob_.3 is misspelt as OUB rather than UOB. 

You can see the currently given modifier below on the left, with the one tested with the corrected scope on the right. 

Also on that note there seems to be an extra space between Oxford and (Union in the tested Dynamic Modifier. I think is caused by an extra space in the loc file for the treaty: ENG_oxford_treaty_dynamic: "Treaty of Oxford " (which quickly testing does seem to cause it).

### Screenshots

![UoB Oxford Treaty Scope](https://github.com/user-attachments/assets/ae246ce1-379b-443d-b994-3635d66e8c86)

### Save File

[UoB Oxford Treaty.zip](https://github.com/user-attachments/files/16467435/UoB.Oxford.Treaty.zip)

### Log Files

[game.log](https://github.com/user-attachments/files/16467436/game.log)
[error.log](https://github.com/user-attachments/files/16467437/error.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Thank you fixed
