### ISSUE TITLE
ENG - Various Event Typos

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#328]
**Quick questions**
HOI4 version: Bolivar v1.14.7.f4d3 (f03b)
Kalterkrieg version: 0.1.3
List any other mods used: TWR Music Mod

**Explanation of the issue:**
Found a couple typos in various ENG events:

1. krg_end.0: In the second option (krg_end.0.b), 'i' is not capitalized
2. krg_end.35: In the third paragraph there is a space between the double line break (\n\n) and the first word, From, and it leaves the paragraph slightly indented.
3. krg_end.26: Saor Éire is misspelled in the even as Soar Erie. 
4. krg_end.25: In the first event option (krg_end.25.a), didn't is misspelled as didnt. (that also appears in a couple other spots in ENG's file and in a NATO event which I included in the screenshot, but if it's better I make another ticket for those please let me know).

**Screenshots:**
![ENG Loc](https://github.com/user-attachments/assets/c6de6d62-0b77-4e35-8097-dfee6adf7e2a)

**Comment by thelilh** [comment]
Thank you for reporting this Yularen. Alongside what you reported, I've now fixed won't, can't, don't, etc across the project
