### ISSUE TITLE
GER - Missing Loc in Event

### ISSUE THREAD

**Issue by sagirismet** [kalterkrieg/Kalterkrieg-bug-reports#329]
### OS

Windows 10

### HOI4 Version

1.14.7 

### Kalterkrieg Version

1.3

### List any other mods used

-

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

All except 3 dlc given for free

### Explanation of the Issue

There is no text in the event when playing Germany

### Possible Cause

-

### Screenshots

![image](https://github.com/user-attachments/assets/7f2491c0-c166-4f47-b129-bb1c649291ea)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Added to our tracker. Thanks for reporting!
