### ISSUE TITLE
ENG - Event Triggers Twice

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#331]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

TWR Music Mod

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

This very well could not be a bug and is working as intended, hence why I'm weary to make tickets like this, or call it a bug and not a suggestion!... but krg_eng.51: "Violence begins to subside" triggers twice. 

### Steps to reproduce

1. Play as ENG until Eden gets shot
2. The last event in that event chain (krg_eng.95: "Nationalists & Syndicalists fight across the country") will trigger an event (krg_eng.51) 90 days later
3. That last event also unlocks the focus Firearms & Paramilitaries Debate; take and complete it.
4. Do not pass the Act. The later choices of 'Arrest their Leaders ...' and 'They're protecting' both will end up triggering the event so pick either.
5. With the trigger from both that last event in the chain and from not passing the act, krg_eng.51 will trigger twice.

### Possible Cause

Again, unless it's WAI, I think it needs a 'fire_only_once = yes' added above triggered only = yes since a player may trigger it two of the three times it can be.

### Screenshots

![Violence Subsides Triggers Twice](https://github.com/user-attachments/assets/733cc572-434a-4726-bbbf-3492a527d46a)
Showing both times it was triggered.
![Violence Subsides Triggers Twice 2](https://github.com/user-attachments/assets/85452543-06b3-4864-a639-2536f2f5b871)
Code snippet.

### Save File

[Violence Subsides First.zip](https://github.com/user-attachments/files/16478121/Violence.Subsides.First.zip)
This is when it triggered the first time for me.
[Violence Subsides Second.zip](https://github.com/user-attachments/files/16478122/Violence.Subsides.Second.zip)
and this the second.

### Log Files

[error.log](https://github.com/user-attachments/files/16478123/error.log)
[game.log](https://github.com/user-attachments/files/16478124/game.log)
I don't know if the game log records literally everything or not, but you won't see the event trigger either time in there. Also not in the error file either, so...

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
@Axolotl3823 this could be a good mentee tas
