### ISSUE TITLE
ENG - 1950 Election Event Chain Triggers Twice

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#332]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

TWR Music Mod

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

The 1950 election chain can trigger twice under a certain circumstance. If the focus 'Prepare for the General Election' (ENG_prepare_the_general_election) completes while the decision 'Meeting Expectations' (ENG_national_government_meet_expectations) is still active with less than 50 days left, the decision times out and fails. As the decision failing will complete the focus, it complete twices, and the event krg_eng.140.t: "Parliament is Adjourned" will trigger twice, a day apart.

But, I will add this can actually be negated if the event option is not selected until the focus 'completes' again (waiting a day without choosing the option), since the event is already triggered and open it won't trigger once more (in my experience).

### Steps to reproduce

1. Play as ENG and in the run up to the 1950 election, keep Bills passed at 6 or less. Do NOT reach 7 as is a requirement to complete the decision 'Meeting Expectations'.
2. Complete the focus 'Prepare for the General Election' while the decision 'Meeting Expectations' has less than 50 days left until it times out.
3. The event krg_eng.140.t: "Parliament is Adjourned" will trigger when the focus completes; choose the event's option.
4. The focus' completion will shave 50 days off the time left for the decision, causing it to fail the next day. It failing will complete the focus again, as that is one of its effects, and will give the event, again (since it's triggered from the focus completion).

### Possible Cause

Most likely because it's allowed to trigger more than once without having 'fire_only_once = yes' added above triggered only = yes. 
Like my other ticket, I'd also suggest adding it in, for the million to one case like this that it might occur in.

### Screenshots

![Completes Twice](https://github.com/user-attachments/assets/77bd157c-88ba-4e0f-a108-0a30e0363146)
But as I was trying to get both events to show at the same time (by letting time go to another day), the event won't trigger again if already on the screen so only one is shown.

### Save File

[Prepare Almost Completed.zip](https://github.com/user-attachments/files/16479038/Prepare.Almost.Completed.zip)
This is the day before the focus ends. The next day it will complete, with the notification and event popup it has (make sure to select the option in the event). The next day after that the decision will kick in and 'complete' the focus again, with the same notification and event popup.

### Log Files

[error.log](https://github.com/user-attachments/files/16479033/error.log)
[game.log](https://github.com/user-attachments/files/16479035/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
