### ISSUE TITLE
ENG - Event Missing a Word

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#333]
**Quick questions**
HOI4 version: Bolivar v1.14.7.f4d3 (f03b)
Kalterkrieg version: 0.1.3
List any other mods used: TWR Music Mod

**Explanation of the issue:**
Taking the intro at the top literally this would be a 'Bug' ticket, so apologies if it should be, but I think it really is just a minor text adjustment. 
For the event krg_eng.46.t: "Voting on the Firearms & Paramilitaries Act", there seems to be a missing word in the last paragraph:

> After 20 excruciating, the results were read..."

I think there should be the word 'minutes' after 20. 

**Screenshots:**
![Missing Word](https://github.com/user-attachments/assets/0140ce13-88e6-446f-bec9-91d18958f338)
(Don't ask why some lines in VSC show up as red)

**Comment by Kennedy2523** [comment]
Fixed.
