### ISSUE TITLE
NAM - Stray §! Desc Text Color Issue

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#334]
**Quick questions**
HOI4 version: Bolivar v1.14.7.f4d3 (f03b)
Kalterkrieg version: 0.1.3
List any other mods used: TWR Music Mod

**Explanation of the issue:**
In two leader bios for Southwest Afrika, Hans-Bogislav Graf von Schwerin-Löwitz (POLITICS_HANS_BOGISLAV_GRAF_VON_SCHWERIN_DESC) & Wolfgang Schenck (POLITICS_WOLFGANG_SCHENCK_DESC), there is a stray Section Symbol and Exclamation Point (§!) causing a color difference in the text.

Removing the extra §! seems to fix the issue (original and tested shown below).

**Screenshots:**
![Bio Desc Colors](https://github.com/user-attachments/assets/1f70023f-bb0c-440a-8a3b-67005697d9cd)

**Comment by Kennedy2523** [comment]
Fixed, thanks Yularen!
