### ISSUE TITLE
MAF - Typo in an Event's [GetLeader]

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#335]
**Quick questions**
HOI4 version: Bolivar v1.14.7.f4d3 (f03b)
Kalterkrieg version: 0.1.3
List any other mods used: TWR Music Mod

**Explanation of the issue:**
In the World News event (MAF_news.7) about the dissolution of Mittelafrika, there is a missing r in [MAF.GetLeade**r**Name] so the former Governor's name is missing in the event description. 

**Screenshots:**
![MAF World News Event](https://github.com/user-attachments/assets/73ef9a85-3a44-42fa-a169-656a62bf7072)

**Comment by thelilh** [comment]
Fixed, will be appearing in the next patch
