### ISSUE TITLE
ENG - Wrong Event Desc

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#337]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

0.1.3

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

The event where Herbert Samuel resigns as Liberal Leader (krg_eng.170 "Herbert Samuel resigns as Liberal Leader") gives the wrong desc - rather than resigning as the Liberal Alliance Leader it says he resigns as Prime Minister. It does not change anything game related as it does give the correct option.

### Steps to reproduce

The event triggers for all paths actually, and I think will happen this way as well with a Democratic-Labour govt, but my example is with an Eden government.

1. Elect the Conservatives in the 1950 election, either as a Majority or with a Hung Parliament.
2. Wait the 616-636 days and the event will trigger

### Possible Cause

I think it's because the way the desc code is set up. Rather than have one section it is split into two, and maybe the game is only reading one of them?

### Screenshots

![Wrong Desc](https://github.com/user-attachments/assets/08bb6efd-06b3-4b06-9095-719829a7fcd2)
![Code](https://github.com/user-attachments/assets/d9146689-feef-4a4f-aa12-247b7fb83e9f)
(Whoops, wanted to include the code here too)

### Save File

[Lib Leader Event Desc.zip](https://github.com/user-attachments/files/16502637/Lib.Leader.Event.Desc.zip)
The save is when the event triggered.

### Log Files

[game.log](https://github.com/user-attachments/files/16502660/game.log)
[error.log](https://github.com/user-attachments/files/16502661/error.log)
The logs are the day after, to take into effect the event.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
