### ISSUE TITLE
DNF - Space missions missing

### ISSUE THREAD

**Issue by Nevark-1** [kalterkrieg/Kalterkrieg-bug-reports#34]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

whichever was the one after release since i hadnt shut down the game

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

arms against tyranny and trial of alleigence

### Explanation of the Issue

First one is during the 1952 elections in austria 2 of the decisions dont do anything except cost political power (the rest of the elections were working normal)
Second is the focus "The Orient Express Reborn" shows "Invalid event with id: krg_dnf_post_el.70
and the third one is after doing the focus "To the Moon" no decisions appear
also i went balaton bloc both times 

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174732619/f3b0d736-8c84-4366-8faf-f58b16108573)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174732619/4dadcc88-8eab-4c00-ad51-fd3bbf41d975)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174732619/42bf4ffc-1853-494b-94f8-26ce112d9768)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174732619/aef5754e-51fe-4d7e-b787-03d2bdfca428)

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174732619/7df7fa52-6239-4e98-bba9-e3fcd87c3e52)

### Save File

[save game.zip](https://github.com/user-attachments/files/16101288/save.game.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16101296/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
no decisions are in DNF_Danubian_Space_Program_cat

**Comment by Flizzyclone** [comment]
Regarding:
> First one is during the 1952 elections in austria 2 of the decisions dont do anything except cost political power

They both fire events on decision timeout.

**Comment by MrCovenant000** [comment]
Space missions will come when we get a space mechanic
