### ISSUE TITLE
ENT/ENG - Entente Leader Events triggers for the UK too Early

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#340]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

TWR Music Mod

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

During the Avalon Event Chain, I as the UK was getting all the events meant for Canada as leader of the Entente.

### Steps to reproduce

If it's true what I believe is causing it:

1. As ENG complete the 1950 election and elect any party, minority or majority.
2. Complete the focus ENG_our_seat_at_the_table: "Our Seat at The Table", which will free the UK from being a puppet of Canada, and make it a full member of the Accord.
3. This, I presume, sets ENG as leader of the Accord (back end code) and therefore leader of the Entente (but not the faction). You can also tell this by tagging to ENT, and it should tag switch you to ENG. 

### Possible Cause

The mod seems to recognize another tag than Canada (in this case me as the ENG) as the leader of the Entente (ENT). Not the faction (as Canada still leads it) but as leader of the Entente and user of the tag alias ENT. It has to do with (and I'm quoting Axolotl here, who was kind enough to confirm it was not intended) "scoping to ENT and because the UK can become ENT before Avalon this causes issues".

I think it has to do with when the Accord scripted effect ENT_accord_set_leader goes into effect, specifically after ENG can become free of Canada, which can happen before Avalon if the player chooses, as it also sets KRG_entente_leader.

The saves and logs are from the Avalon Chain where I was getting some events twice, one meant for the ENT leader and one for the UK/ENG, allowing me to choose the path the event chain can takes, rather than the intended Canada.

### Screenshots

![ENT = ENG - not Canada](https://github.com/user-attachments/assets/06870aa3-e64f-4355-bc90-27429388d95c)

### Save File

[Canadian Event Maybe.zip](https://github.com/user-attachments/files/16507501/Canadian.Event.Maybe.zip)

### Log Files

[game.log](https://github.com/user-attachments/files/16507502/game.log)
[error.log](https://github.com/user-attachments/files/16507503/error.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
The fix here is should be simple by going through and either fixing the scope to be either Canada or checking if the UK is ENT and triggered to CAN then. It depends if the events are written to be Canada focused or ENT in general

**Comment by ghost** [comment]
For the latter, I should have noted that originally: I think they were written to be Canadian focused. Even though many in the chain  just use the generic 'Accord' when referencing the alliance, so not the leader, the event which triggers after the one in the screenshot does reference 'the Canadians' (krg_engdip.71) (which I've edited into the screenshot, along with snippets of the loc to show it's not using [GET.ENT...] or anything like that (for the one on the right. The one on the left to show the event is talking about British even though they get the event).

**Comment by Axolotl3823** [comment]
fixed
