### ISSUE TITLE
Game crashing when starting

### ISSUE THREAD

**Issue by B211NAN** [kalterkrieg/Kalterkrieg-bug-reports#341]
### OS

Windows 11

### HOI4 Version

latest of august 2024

### Kalterkrieg Version

latest of august 2024

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

trial of allegience

### Explanation of the Issue

after downloading the mod and starting it, i recived a notification of windows about a download for hoi 4. usually i do not recive this type of notification. i have inspected it and thought that i should block it always. After that tha game crashes every time i start it with mods or without. Can you guys help me out figuring what should i do ? P.S. i have also reinstalled the game but this still happens

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by MrCovenant000** [comment]
were you using any other mods?

**Comment by MrCovenant000** [comment]
and where did you download our mod

**Comment by B211NAN** [comment]
Not using any other mode when this happend but i also had crashes when starting the other modes i use. 
I have downloaded the mod from the steam workshop

**Comment by MrCovenant000** [comment]
I would reccomend verifying your game files as it sounds like your base game has issues
