### ISSUE TITLE
ENG - Missing Idea Picture

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#342]
**Quick questions**
HOI4 version:  Bolivar v1.14.7.f4d3 (f03b)
Kalterkrieg version: 0.1.3

**Describe the specific change you would like:**
Currently, one of the UK's three Chiefs of Staff ideas, Harding's (which has four versions: ENG_hardings_army_1 through ENG_hardings_army_4), does not have a picture associated with it, and I think the same picture used for the other two, advisors_ENG (Gale's shown below) should be used.

**Explain the reasoning behind this actionable change:**
Just for conformity's sake since this was probably just a little oversight. 

**Additional context or comments:**
![Idea Picture Suggestion](https://github.com/user-attachments/assets/198e4ab2-ee6c-4ada-b5d3-95bc14d04ce2)

**Comment by Axolotl3823** [comment]
fixed
