### ISSUE TITLE
ENG - Double Economic Recovery Plan Idea (Conservatives)

### ISSUE THREAD

**Issue by ghost** [kalterkrieg/Kalterkrieg-bug-reports#343]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1.3

### List any other mods used

TWR Music Mod

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

N/A

### Explanation of the Issue

When completing either of the 1950 Conservative Economic Recovery Plan foci (ENG_tory_1950_lyttelton_plan: "Lyttelton's Plan", or ENG_tory_1950_butler_plan: "Butler's Plan") both give their respective ideas twice, one as a dynamic and one as a regular one. Butler's is shown for this ticket.

So what happens is you get the initial idea effects twice, and the idea with '(United Kingdom)' after it will be updated as you progress through the tree. But the static one is the one with a desc actually.

### Steps to reproduce

1. Elect the Conservatives in the 1950 election
2. Take the focus "Lyttelton's Plan" or "Butler's Plan" 
3. Upon completion, two ideas will be given, both with the same name '... Economic Recovery Plan', but the dynamic one will have the country name after it.

### Possible Cause

Axolotl was kind enough to confirm it for me, but this has to do with the way the idea was originally written, then changed before release, so the idea which shows all the blank effects needs to be removed. 
_I think_ it's ENG_butler_economic_plan, as ENG_butler_economic_plan_dynamic coded and working as it is intended (just the scope needs to be adjusted so it won't have the country name after it). In addition the desc from the former needs to be moved to the latter so it can have a desc.

### Screenshots

![Two Econ Ideas](https://github.com/user-attachments/assets/e8a7bd00-5682-4aad-b884-8f688b7dbf71)

### Save File

[Economic Recovery Plan Issue.zip](https://github.com/user-attachments/files/16534286/Economic.Recovery.Plan.Issue.zip)
The save is the day before the focus completes.

### Log Files

[game.log](https://github.com/user-attachments/files/16534288/game.log)
[error.log](https://github.com/user-attachments/files/16534289/error.log)
The log files are the day after the focus completes.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
