### ISSUE TITLE
GER - Supercarrier Doctrine idea not working properly

### ISSUE THREAD

**Issue by GeorgeZhou3** [kalterkrieg/Kalterkrieg-bug-reports#35]
### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/105748094/2af9add0-c7a4-438f-9bb9-e0d89474349d)
The deck_size modifier is a flat increase, so adding 0.25 deck_size just adds 2 planes to the carrier.  

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
fixed
