### ISSUE TITLE
game crushed while loading 

### ISSUE THREAD

**Issue by Kasava-jpg** [kalterkrieg/Kalterkrieg-bug-reports#354]
**Quick questions**
OS:
HOI4 version:1.15
Kalterkrieg version: 0.1.3
List any other mods used:
Were you using Steam? Yes
Were you in multiplayer? No
Which expansions do you NOT have?

**Explanation of the issue:**
My game crushed while loading, it says something wrong with map definitions 

**Steps to reproduce:**

1.

2.

**Possible cause:**

**Screenshots:**
![image](https://github.com/user-attachments/assets/291051c3-e47a-4fac-b3a0-d310a6db0e38)

**Comment by Axolotl3823** [comment]
The mod is not yet updated to the latest version, if you want to play you need to role back the game version
