### ISSUE TITLE
TEX - Scripted Localization Error in TEX Primaries

### ISSUE THREAD

**Issue by BestestIffers** [kalterkrieg/Kalterkrieg-bug-reports#37]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

plpc

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

toa

### Explanation of the Issue

scripted effect error text appears after Georgia primaries event

### Steps to reproduce

Play as TEX, pov of conservatives, and get to georgia primaries

### Possible Cause

unsure

### Screenshots

![TEX Scripted Effects Error](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/20ec4668-8dd8-4908-93b1-df69a9fccb73)

### Log Files

[error.log](https://github.com/user-attachments/files/16101471/error.log)
[game.log](https://github.com/user-attachments/files/16101474/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment]
Fixed
