### ISSUE TITLE
Sweden - Social democrats are wrongly named and capitalization does not follow Swedish grammar rules

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#38]
**Quick questions**
HOI4 version: 
1.14.7

Kalterkrieg version: 
0.1

List any other mods used:
None

**Explanation of the issue:**
The social democrats of Sweden should be called Socialdemokraterna (literally "the social democrats") instead of Socialdemokratiska which means "the social democratic". The full names of all parties should have only the first letter of the first word capitalized, so "Sveriges Socialdemokratiska Arbetareparti" should instead be "Sveriges socialdemokratiska arbetareparti", the same for all other parties (SocCon and AuthDem are perfectly correct though).

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/c5db93a0-e03b-43ff-8bc3-a7c159ddae6e)
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/f4f93f00-2507-4db1-a9ad-bc8e7dbf5bdd)

**Comment by Kennedy2523** [comment]
Fixed. This is my fault, sorry Leaf
