### ISSUE TITLE
AUS- Air Tree Buged

### ISSUE THREAD

**Issue by TheAdrianbbc** [kalterkrieg/Kalterkrieg-bug-reports#39]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

 all in Official Kalterkrieg Collection and maybe State Transfer Tool

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have everything

### Explanation of the Issue

Air focus tree should be exclusive like navy but you can pick both options. I used focus.autocomplete to check

### Screenshots

![AUS Air](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174735003/50e93707-194e-46e7-b254-f9d059d8b32b)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
