### ISSUE TITLE
AST - Australasia turned into a Republic

### ISSUE THREAD

**Issue by wxllops** [kalterkrieg/Kalterkrieg-bug-reports#4]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

1

### List any other mods used

unit submods, fps mod & realistic nukes

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

n/a

### Explanation of the Issue

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/40343857/389bdca9-4550-4102-af58-7838f13766fb)
country name is wrong after chifley won election, presume is a cosmetic tag problem so what its under bugs.

### Steps to reproduce

ben chifley must win the australasian election

### Possible Cause

localisation for socdem australasian name

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/40343857/de68b70a-e4c0-48da-b44d-418181b18a0f)

### Save File

it really doesnt need them

### Log Files

it really doesnt need them

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by MrCovenant000** [comment]
Are you playing with any other mods?

**Comment by wxllops** [comment]
never mind! my hoi4 was in fact just buggin on its own.
