### ISSUE TITLE
TEX - possible typo

### ISSUE THREAD

**Issue by ffffffffdsfsdrf3** [kalterkrieg/Kalterkrieg-bug-reports#40]
**Quick questions**
HOI4 version: Latest as of 2024/07/04
Kalterkrieg version: Latest as of 2024/07/04
List any other mods used: N/A

**Explanation of the issue:**
In the AUS, during the event "AFP Convention - The Debate" during the second election, I believe the button that should support the progressives is switched wit the conservatives, and vice versa

**Screenshots:**

![hoi4_9](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/92403179/16bacad9-5a15-436d-9193-eeef4db7dd83)

(Orthodox working as intended)

![hoi4_10](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/92403179/83612e52-b7ed-46ed-b0d7-977f294a7144)

(Button text supports Strom and the tories, yet give delegates to the progressives)

![hoi4_11](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/92403179/cf78e2b2-6f63-4189-b3ce-d74b54ddf7f5)

(Button text supports McMath and the Progressives, yet gives delegates to the tories)

Side Note - How can I find the exact event number, not just the title, to make bug reports more convenient for everyone?

**Comment by Kennedy2523** [comment]
Fixed.
