### ISSUE TITLE
CAN - Montgomery Plan Bug 

### ISSUE THREAD

**Issue by panzers31** [kalterkrieg/Kalterkrieg-bug-reports#42]
### OS

windows 10

### Were you using Steam?

yes

### Explanation of the Issue

When selecting the  Montgomery plan as Canada for Republican France and The Spanish Republic. It doesnt do anything.

### Steps to reproduce

After doing the focus tree just select the decision, unlike Portugal and the UK, a national spirit doesnt pop

### Save File

[CAN_1948_10_31_11.zip](https://github.com/user-attachments/files/16101535/CAN_1948_10_31_11.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16101536/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
I have confirmed the spirits add for every country. This might better be classified as an interface bug as you cannot see all the SPR spirits. Independently fixed the issue of factories being built in the middle of wherever.
