### ISSUE TITLE
TEX - AFP Convention Debate, incorrect loc

### ISSUE THREAD

**Issue by BestestIffers** [kalterkrieg/Kalterkrieg-bug-reports#44]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: toa

**Explanation of the issue:** Options 2 and 3 for 1952 elections convention debate are wrong. 2 should be pogressives and 3 should be conservatives

**Screenshots:**
![Typo 1](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/d3184591-da25-4364-81ac-708b13e230c6)

**Comment by BestestIffers** [comment]
![Holt Win 3ACW](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/7928604e-c6ac-4982-b878-fd445162da27)
This victory event has 2 event options displayed

**Comment by Kennedy2523** [comment]
Fixed.
