### ISSUE TITLE
MAF - Several Decisions Working Incorrectly in a Hippel Run

### ISSUE THREAD

**Issue by ForTheImperium** [kalterkrieg/Kalterkrieg-bug-reports#45]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

KR models, KR music, KR-KRG models compatibility, and Square Unit Counters

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

BBA, AAT, ToA

### Explanation of the Issue

Decisions working incorrectly in a Hippel run:

1. "Cement Military Presence in Kamerun" (a) has "(Corse, Lazio, Switzerland and 1160 others):" in its description and (b) crashes the game if I later pick "switch to Sudwestafrika" but not if I switch to Tanganjika.
(Also, the country released this way is named just Kamerun, not Herrschaftsgebiet of Kamerun. I'm not sure if it's a glitch though; I guess Herrschaftsgebiet of Kamerun is way too long to fit on the map?)

2. "Cement Military Presence in Togoland" (a) has the same "(Corse, Lazio, Switzerland and 1160 others):" issue, (b) is incorrectly labelled "Cement Military Presence in Kamerun", (c) renames MAF to a yellow "We will deploy forces to assure a Pro-German Togoland prevails" on the diplomacy screen and "HWe will deploy forces to assure a Pro-German Togoland prevails!" on the map, and (d) does not properly work - when MAF dissolves, Togoland is still called the Republic of Togoland as it will be if the decision hasn't been selected - though a different party rules it - even after the decision has been selected. It also does not have any Reichspakt tie, unlike Kamerun.
3. "Destroy Ugandan Republicans" (a) also has the "(Corse, Lazio, Switzerland and 1160 others):" thing and (b) crashes the game if I later pick "switch to Tanganjika " but not if I switch to Sudwestafrika.

### Steps to reproduce

Kamerun decision + switch to Sudwestafrika = crash
Uganda decision + switch to Tanganjika = crash

### Possible Cause

I have no idea at all

### Screenshots

<img width="259" alt="Kamerun" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/ea27d889-df0e-48af-a6c5-bd8f0ec3451c">
<img width="257" alt="Togoland" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/39695063-0c66-4e83-80ff-c2a70a75be92">
<img width="236" alt="Uganda" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/effab603-cde7-4e5a-9e01-d85e10f1993b">

### Save File

[MAF_1952_10_20_06.zip](https://github.com/user-attachments/files/16102087/MAF_1952_10_20_06.zip)

### Log Files

[error_Kam+Sud.log](https://github.com/user-attachments/files/16102123/error_Kam%2BSud.log)
[error_Uga+Tan.log](https://github.com/user-attachments/files/16102125/error_Uga%2BTan.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
