### ISSUE TITLE
GER - Event, Collapse of the Grand Coalition, clunky sentence

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#47]
**Quick questions**
HOI4 version:
1.14.7
Kalterkrieg version:
0.1
List any other mods used:
None

**Explanation of the issue:**
The sentence shown in picture is a bit clunky. 

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/8cf50d49-9530-481f-aa76-9b2ec22d9ff0)

**Comment by Kennedy2523** [comment]
Fixed.
