### ISSUE TITLE
GER - Event: The Deutsches Heer, minor typo

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#48]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Minor spelling mistake in the event. "Are lurking" or "lurks" would work.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/5ccb311e-dc96-495b-ada1-e23217e40443)

**Comment by Kennedy2523** [comment]
Fixed.
