### ISSUE TITLE
The Game crashes while creating Checksum on Steam Deck via Linux Native version

### ISSUE THREAD

**Issue by Regalia776** [kalterkrieg/Kalterkrieg-bug-reports#5]
**Quick questions**
OS: SteamOS
HOI4 version: Bolivar 1.14.7
Kaiserreich version: 0.1
List any other mods used: None
Were you using Steam? Yes
Were you in multiplayer? No
Checksum (four-letter code at the bottom of your title menu): N/A (cannot get that far)
Which expansions do you NOT have? None, all are active due to subscription

**Explanation of the issue:**
Game crashes at Creating Checksum during loading, install is fresh, installed the same day. Version is Linux-native. Launcher won´t work through Proton.

**Steps to reproduce:**
Just try to launch the mod on Steam Deck.
1.

2.

**Other info:**

**Possible cause:**

**Log file:**

**Comment by Tom-Dude** [comment]
I have the exact same issue.

OS: Linux Mint 21.3
HOI4 Version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: None
Were you using Steam? Yes
Were you in multiplayer? No
Checksum (four-letter code at the bottom of your title menu): None (crashes)
Which expansions do you NOT have? None, I have all expansions

**Comment by alinur-s** [comment]
^^ Same here

- Distribution: Ubuntu 24.04 LTS
- HOI4 Version: 1.14.7.f4d3
- Kalterkrieg version: 0.1
- No other mods used
- On Steam

[**system.log**](https://github.com/user-attachments/files/16100702/system.log)
[**error.log**](https://github.com/user-attachments/files/16100757/error.log)

**Comment by Regalia776** [comment]
I can now confirm the same thing happening on my laptop.

OS: Solus 4.5
HoI4 Version: 1.14.7 Bolivar
Kalterkrieg version: 0.1
Other mods: None
DLC: All

**Comment by OrionIV** [comment]
Same here

OS: SteamOS
HOI4 version: Bolivar 1.14.7
Kaiserreich version: 0.1
List any other mods used: None
Were you using Steam? Yes
Were you in multiplayer? No
Checksum (four-letter code at the bottom of your title menu): N/A (cannot get that far)
Which expansions do you NOT have? NSB, BBA, AAT

**Comment by Flizzyclone** [comment]
Linux should now function fine.

**Comment by OrionIV** [comment]
Are we getting the fix soon, or we have to wait for the next hotfix?

**Comment by Flizzyclone** [comment]
@OrionIV 
> Are we getting the fix soon, or we have to wait for the next hotfix?

Should already be out there. Try deleting and resubscribing to the mod if it does not work. (There is reason to believe the fix may not automatically apply without a reinstall, even if you do update.)

**Comment by OrionIV** [comment]
Indeed, resubscribing fixed the crash.
