### ISSUE TITLE
GER - Event: The Bristol Incident, minor typo

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#50]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
"Generalfeldmarshal" should be "Generalfeldmarschall"

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/c9a58a1e-f71e-4a48-86bf-6c30d4ed32a4)

**Comment by aggebojkalos** [comment]
This is an issue on more events by the way

**Comment by Kennedy2523** [comment]
Fixed on all events.
