### ISSUE TITLE
GER - Event: Our Demands, minor typo and grammar issue

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#51]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
There should be a space after the comma under the arrow and the colon does not really work in the underlined sentence (I think a semi-colon and removing the "and" would work well).

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/2c116997-3405-4942-ab50-6ca214cf2501)

**Comment by Kennedy2523** [comment]
Fixed.
