### ISSUE TITLE
GER - Event: Neurath Returns to Germany, minor spelling mistakes

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#52]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
"Received" is misspelled as "recieved". "_hero's_" or "_heroes'_" would work better than "heroes". Double space after "nation", is highlighted on the picture linked. Maybe a comma after "back", too?

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/4d7c85a6-fe4c-44f9-aef1-5fdd15f1c287)

**Comment by Kennedy2523** [comment]
Fixed.
