### ISSUE TITLE
Any country - Minor grammar mistake on news popup

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#53]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Genitive case of "it" is "its". This might pop up in many places, legit super easy mistake to make.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/2ea8570e-6c46-4100-8336-946dc05172f3)

**Comment by Kennedy2523** [comment]
Fixed.
