### ISSUE TITLE
GER -- Reichstag seat changes not occurring, Bredow dies without being sent to Koln

### ISSUE THREAD

**Issue by aleisner** [kalterkrieg/Kalterkrieg-bug-reports#54]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Kaiserreich unit pack

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

By Blood Alone, Arms Against Tyranny, Trial of Allegiance

### Explanation of the Issue

The events for the defections from the SPD and LVP fired but the seat numbers in the Reichstag did not change and the number of seats in support of the government stayed the same as well.
Secondly, I choose to keep Bredow in Berlin during the Koln crisis, however after the negotiations started I got an event where he was blown up in Koln anyway, I had to pick a different head of government and was forced onto a new path.

### Steps to reproduce

Take the "Split the Demokratische Union" focus and take the decisions which trigger the defection events, the decisions are "split the liberals" for the LVP and "Fund the DNAP". Click through the events describing the defections and check the party numbers in the Reichstag section of the decision tab. 
When the Koln crisis starts, select the support the police event. Then in the who to send event choose to keep Bradow in Berlin. Wait for the negotiation events to fire until eventually the Bredow assassination event occurs.

### Save File

[GER_1948_11_11_07.zip](https://github.com/user-attachments/files/16102493/GER_1948_11_11_07.zip)

### Log Files

[error.log](https://github.com/user-attachments/files/16102497/error.log)
[game.log](https://github.com/user-attachments/files/16102501/game.log)
[setup.log](https://github.com/user-attachments/files/16102503/setup.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Bredow blowing up has been fixed, was jus a loc issue
