### ISSUE TITLE
Land doctrine in combined operations contains debug names.

### ISSUE THREAD

**Issue by RedHodge** [kalterkrieg/Kalterkrieg-bug-reports#57]
**Quick questions**
HOI4 version:
Kalterkrieg version:
List any other mods used:

**Explanation of the issue:**
The doctrine "logistics support" contains debug names

**Screenshots:**
![image_2024-07-05_003807323](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171615470/b37ec766-84cc-4c65-8e2e-1f571779a7b3)

**Comment by Kennedy2523** [comment]
Fixed! Thanks for the report
