### ISSUE TITLE
Event: Successor of Thyssen's details are called place holder

### ISSUE THREAD

**Issue by RedHodge** [kalterkrieg/Kalterkrieg-bug-reports#58]
**Quick questions**
HOI4 version: 1.14
Kalterkrieg version: idk
List any other mods used: some music mods

**Explanation of the issue:**
Event: Successor of Thyssen's details are called place holder

**Screenshots:**
![Screenshot 2024-07-05 003705](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171615470/598a1d70-4016-486f-aed9-f51a63032d9b)

**Comment by Kennedy2523** [comment]
This is a placeholder description and will be added in a future update.
