### ISSUE TITLE
Germany - Event "Hans von Shwerin appointed in Windhuk" contains a placeholder in the details

### ISSUE THREAD

**Issue by RedHodge** [kalterkrieg/Kalterkrieg-bug-reports#59]
**Quick questions**
HOI4 version: 1.14
Kalterkrieg version: idfk
List any other mods used: Music mods

**Explanation of the issue:**
Event "Hans von Shwerin appointed in Windhuk" contains a placeholder in the details

**Screenshots:**
![Screenshot 2024-07-05 004734](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171615470/5e5c9812-63f5-430f-924b-afd0b215e872)

**Comment by Kennedy2523** [comment]
THis is a placeholder description and will be added in a future update.
