### ISSUE TITLE
Heimdallr's Violent Peace - a minor writing error

### ISSUE THREAD

**Issue by trooper828xx** [kalterkrieg/Kalterkrieg-bug-reports#6]
**Quick questions**
HOI4 version: 1.14.7
Kalterkrieg version: 0.1
List any other mods used: Spot Optimization

**Explanation of the issue:**
Small text error, perhaps a missing word. In the second paragraph, 4th sentence it says "On our Eastern our Ost-Wall allies..." Likely should be "On our eastern flank" I assume. 

Additionally, the line "...the left bank Rhineland" reads a bit off to me i suggest "left bank of the Rhine" referring to the river rather than the Rhineland which would be the territories the river flows through and can't necessarily have a "left bank".

The Last sentence in the second paragraph too reads oddly, i will suggest a rewrite - "Without a Danubian intervention the question of our great victory hung over our heads. It was through their efforts that the east was saved, and the International was defeated."

Something like that can likely improve the quality of the writing there. 

**Screenshots:**
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/32004757/7e133f25-a959-4cc4-9494-ca8a27276b41)

**Comment by trooper828xx** [comment]
Apologies if i am using the error type incorrectly, i have literally never used github beyond making commits to old projects lol

**Comment by Kennedy2523** [comment]
Fixed. Thank you for the report!
