### ISSUE TITLE
Germany - Event "Berlin holds fast" contains no details whatsoever

### ISSUE THREAD

**Issue by RedHodge** [kalterkrieg/Kalterkrieg-bug-reports#62]
**Quick questions**
HOI4 version: 1.14
Kalterkrieg version: idk
List any other mods used: Music mods

**Explanation of the issue:**
Event "Berlin holds fast" contains no details whatsoever

**Screenshots:**
![Screenshot 2024-07-05 005234](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/171615470/218269e5-4f9f-4c8b-8a75-652f5d372df1)

**Comment by Kennedy2523** [comment]
This is an unfinished event and will be added in due time.
