### ISSUE TITLE
DNF - Wien instead of vienna in localisation desc id

### ISSUE THREAD

**Issue by Sprilly** [kalterkrieg/Kalterkrieg-bug-reports#63]
### Explanation of the Issue

The Wien to Bucharest in five minutes or less focus has missing loc.

### Possible Cause

The focus has an id "DNF_vienna_to_bucharest" but its description loc has the id "DNF_Wien_to_bucharest_desc", which causes the game to not find the description. Changing the id to DNF_vienna_to_bucharest_desc fixes the issue.

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed. Thanks for your help in solving the issue!
