### ISSUE TITLE
NEWS - Queen Wilhelmina abdicates, minor spelling mistakes

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#64]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
the "a" in "abdicates" should be capitalized, there should be a period at the end of the second paragraph and "later of" should be "the latter of"

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/e06e219e-81df-4d0d-b646-ebe60befddd8)

**Comment by Kennedy2523** [comment]
Fixed/
