### ISSUE TITLE
Cancel Focus Button

### ISSUE THREAD

**Issue by matieo33** [kalterkrieg/Kalterkrieg-bug-reports#65]
HOI4 version: 1.14.6
Kalterkrieg version: 0.1

**Describe the specific change you would like:**
Adding an "X" button that lets u quickly cancel the focus tree
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/61363778/99d7edfc-3b3b-4713-ad02-03b755cdc5e0)

**Explain the reasoning behind this actionable change:**
it makes everything a million times easier

**Additional context or comments:**

**Comment by Flizzyclone** [comment]
done
