### ISSUE TITLE
FRA - Unable to Complete Focus Tree

### ISSUE THREAD

**Issue by BestestIffers** [kalterkrieg/Kalterkrieg-bug-reports#67]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

plpc

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

toa

### Explanation of the Issue

FRA is unable to complete their focus tree if they pick specific foci which lock them out of needed prereqs for The Conseil D'etat finisher

### Steps to reproduce

Play as FRA, follow the screenshotted focus path below

### Possible Cause

This exact path wasn't factored in when designing the tree

### Screenshots

![North France Bug](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/dd5a3e07-1e66-40fd-b147-763855689c31)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
Fixed
