### ISSUE TITLE
GER - Event: Agents Infiltrate the SPD, double space

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#68]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Double space, highlighted

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/9c697bfd-8624-4deb-b9a0-999b40636297)

**Comment by Kennedy2523** [comment]
Fixed. This is actually a very funny issue, thanks for spotting!
