### ISSUE TITLE
GER - Event: SPD Infighting Continues to Rise, missing names

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#70]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Seemingly two names are missing, highlighted. 

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/268e7097-50fb-462d-979a-127bd712b0d0)

**Comment by Kennedy2523** [comment]
fixed
