### ISSUE TITLE
GER - Event: The Madagaskar Revolt

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#71]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted, "is" should be "us".

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/b1a88655-2fb5-41cd-b770-c2b5b4a17459)

**Comment by Kennedy2523** [comment]
Fixed
