### ISSUE TITLE
NEE - Unable to campaign in elections

### ISSUE THREAD

**Issue by sayko06** [kalterkrieg/Kalterkrieg-bug-reports#72]
### OS

Windows 10

### HOI4 Version

v1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

none

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have no DLC

### Explanation of the Issue

I cannot campaign in either the midterm or presidential New England elections. 

### Steps to reproduce

idk

### Possible Cause

It might happen if you have campaigns running after the elections end 

### Screenshots

![hdjwhdjwhdjwhdjwhdjwhdjwdhw](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174749914/90dd3ec7-16ea-4996-815d-74d84baf21a0)

### Save File

[Ironman New England 1.zip](https://github.com/user-attachments/files/16103094/Ironman.New.England.1.zip)

Sorry if this file being ironman is the issue or messes with debugging

### Log Files

[error.log](https://github.com/user-attachments/files/16103103/error.log)
[game.log](https://github.com/user-attachments/files/16103104/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
