### ISSUE TITLE
NEE - Election Season Description

### ISSUE THREAD

**Issue by Nethermob** [kalterkrieg/Kalterkrieg-bug-reports#73]
**Quick questions**
HOI4 version: 1.14.6
Kalterkrieg version: 0.1
List any other mods used: N/A

**Explanation of the issue:**
New England's 1951 midterm text is from the 1949 presidential elections
![image_2024-07-04_185401992](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174747336/32ffb283-01a4-4186-8c48-4bd01a9779a9)

**Screenshots:**

**Comment by Kennedy2523** [comment]
Fixed
