### ISSUE TITLE
GER - Event: Kölnsche Volkszeitung Circulation Falls

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#74]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Event title should say "Kölnische", not "Kölnsche". "It's", "its", yeah.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/6d86e4e1-6dbb-449e-bfeb-5fc3fcd42bb0)

**Comment by Kennedy2523** [comment]
Fixed.
