### ISSUE TITLE
GER - Event: Vorwarts Circulation 'Changes'

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#75]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
"Vorwarts" in the title should be "Vorwärts".

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/5bb4b141-368b-4a95-9465-d596048a5324)

**Comment by Kennedy2523** [comment]
Fixed.
