### ISSUE TITLE
NEE - Cannot finish army tree

### ISSUE THREAD

**Issue by Nethermob** [kalterkrieg/Kalterkrieg-bug-reports#77]
### OS

Windows 11

### HOI4 Version

Current (1.14.6)

### Kalterkrieg Version

0.1

### List any other mods used

N/A

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None (AAT and TFV not enabled)

### Explanation of the Issue

The New England army tree requires focuses that are locked when choosing one of the army paths

### Steps to reproduce

Play New England

### Screenshots

![image_2024-07-04_200751059](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174747336/f4291bfd-9663-4b3d-952e-0991c652892f)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
Fixed internally
