### ISSUE TITLE
Italy - Legge Stralcio Focus

### ISSUE THREAD

**Issue by SolInvictus74** [kalterkrieg/Kalterkrieg-bug-reports#8]
### OS

Win 11

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

I'm using the Official Kalterkrieg Collection

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Alliance

### Explanation of the Issue

The Italian focus "Legge Stralcio" change the category of Yanbian state, which is owned by Beiyang Government

### Possible Cause

The Yanbian State ID was probably confused with an Italian state ID

### Screenshots

![Legge Stralcio](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/141489809/a522ed1e-7332-4fe3-8518-3504c90e1d33)

### Save File

[ITA_1949_09_06_01.zip](https://github.com/user-attachments/files/16099489/ITA_1949_09_06_01.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
someone confused 908 with 918
