### ISSUE TITLE
NEE - Unable to court conservative dems during bill voting

### ISSUE THREAD

**Issue by sayko06** [kalterkrieg/Kalterkrieg-bug-reports#80]
### OS

Windows 10

### HOI4 Version

v1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

none

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have no DLC

### Explanation of the Issue

I am unable to take the "court party" option for the conservative democrats when voting on a bill. I was able to court the republicans, but when I did the republicans disappeared off the bill menu in the decision screen which might be a completely separate bug on its own.

### Steps to reproduce

The subsidized health care bill underneath the Harriman tree is the one that had this bug happen. I made a second save file to make sure this wasn't a fluke and it did happen again (along with the republicans disappearing).

### Possible Cause

idk

### Screenshots

![hdjiwhbhdwhbdwhduwwd](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174749914/2b9e2c75-f9de-4e29-ac39-6cf9b5292468)

### Save File

[Ironman New England 2.zip](https://github.com/user-attachments/files/16103556/Ironman.New.England.2.zip)

### Log Files

[game.log](https://github.com/user-attachments/files/16103551/game.log)
[error.log](https://github.com/user-attachments/files/16103554/error.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
