### ISSUE TITLE
CAL - Missing loc for "The Start of Civil Rights"

### ISSUE THREAD

**Issue by ffffffffdsfsdrf3** [kalterkrieg/Kalterkrieg-bug-reports#81]
### OS

Windows

### HOI4 Version

Latest as of 2024/07/04

### Kalterkrieg Version

Latest as of 2024/07/04

### List any other mods used

N/A

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Explanation of the Issue

"The start of civil rights" event after completing focus "The start of civil rights" focus as PSA has no text.

### Steps to reproduce

Play PSA
Do focus "The start of civil rights"

### Possible Cause

forgot to put the text in.

### Screenshots

![hoi4_12](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/92403179/90b6afe4-0157-419e-b079-3d19fb916faf)

### Save File

Unneeded

### Log Files

Unneeded

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Loc is being added periodically as finished. Thanks for reporting!
