### ISSUE TITLE
GLOBAL - Cannot produce SAM missiles or Ballistic missiles

### ISSUE THREAD

**Issue by TuRux-0** [kalterkrieg/Kalterkrieg-bug-reports#82]
### OS

Windows

### HOI4 Version

Bolivar v1.14.7.f4d3 (f03b)

### Kalterkrieg Version

0.1

### List any other mods used

None

### Were you using Steam?

Yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

Tiral of Alliegence not activated

### Explanation of the Issue

I unlocked the SAM and Ballistic missiles technology but i cannot produce them at all because they do not appear in the production tabs

### Steps to reproduce

Unlock SAM missiles technology or Ballistic missile technology

### Possible Cause

Trials of alliegence not activated?

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/147676765/e94b2d94-344a-4af4-80dd-510ca70dcf60)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/147676765/38700d2b-5e41-41d8-ba88-5f56435a5ee5)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/147676765/b98df65f-a381-4fa0-ad13-8abe8b55214f)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/147676765/76d5d73f-1d4c-47fe-ba29-69bfc6667519)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/147676765/616adac4-e8e4-4423-b646-cd9a7fa340f8)
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/147676765/be1997ca-a57d-4348-a066-b83c8536b4fd)

### Save File

[GER_1948_01_04_11.zip](https://github.com/user-attachments/files/16103760/GER_1948_01_04_11.zip)

### Log Files

[ai.log](https://github.com/user-attachments/files/16103761/ai.log)
[ai_trace.log](https://github.com/user-attachments/files/16103762/ai_trace.log)
[code_revisions.log](https://github.com/user-attachments/files/16103763/code_revisions.log)
[error.log](https://github.com/user-attachments/files/16103764/error.log)
[executed_commands.log](https://github.com/user-attachments/files/16103765/executed_commands.log)
[game.log](https://github.com/user-attachments/files/16103766/game.log)
[graphics.log](https://github.com/user-attachments/files/16103767/graphics.log)
[memory.log](https://github.com/user-attachments/files/16103768/memory.log)
[message.log](https://github.com/user-attachments/files/16103769/message.log)
[posted_commands.log](https://github.com/user-attachments/files/16103770/posted_commands.log)
[random.log](https://github.com/user-attachments/files/16103771/random.log)
[random_1.log](https://github.com/user-attachments/files/16103772/random_1.log)
[random_2.log](https://github.com/user-attachments/files/16103773/random_2.log)
[received_commands.log](https://github.com/user-attachments/files/16103774/received_commands.log)
[scenario_testing.log](https://github.com/user-attachments/files/16103775/scenario_testing.log)
[sent_commands.log](https://github.com/user-attachments/files/16103776/sent_commands.log)
[setup.log](https://github.com/user-attachments/files/16103777/setup.log)
[system.log](https://github.com/user-attachments/files/16103778/system.log)
[system_debug.log](https://github.com/user-attachments/files/16103779/system_debug.log)
[text.log](https://github.com/user-attachments/files/16103780/text.log)
[time.log](https://github.com/user-attachments/files/16103781/time.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed! This one took a while. Thanks for the report
