### ISSUE TITLE
DNF - Nuclear Acquisition Event fires in February 1948

### ISSUE THREAD

**Issue by empressdesuvult** [kalterkrieg/Kalterkrieg-bug-reports#83]
### OS

Windows

### HOI4 Version

Latest

### Kalterkrieg Version

Latest

### List any other mods used

None

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None

### Explanation of the Issue

DNF having the A-Bomb event unintentionally fires in February 1948, skipping the entire DNF nuclear bomb focus tree. This occurred on multiple occasions at the start of every game, whether while playing DNF or not.

### Steps to reproduce

Play game as normal, appears to occur every time.

### Possible Cause

Improper trigger?

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
This is WAD. They get the A-bomb, but the tree is to get an H-bomb I believe.
