### ISSUE TITLE
DNF - Dissolving Balaton Coalition does not remove ingame coalition + Other Issues

### ISSUE THREAD

**Issue by BestestIffers** [kalterkrieg/Kalterkrieg-bug-reports#84]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

plpc

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Which expansions do you NOT have?

toa

### Explanation of the Issue

Focus to dissolve Balaton Bloc coalition removes them from the parliament coalition but not from the political ingame coalition

### Steps to reproduce

Play as liberals and end balaton bloc coalition

### Possible Cause

might be WAD but is a bit weird for them to be in opposition there but not in government?

### Screenshots

![Austria Bug Maybe](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/44e8e5b3-d822-49f2-962e-840ce8d8f342)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by BestestIffers** [comment]
This escalated into full on bug, attaching stuff now.
![Austria Bug Yes](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/e1d66fd8-0b2c-4eba-b8c6-65c84853d3cb)
[error.log](https://github.com/user-attachments/files/16104209/error.log)
[game.log](https://github.com/user-attachments/files/16104211/game.log)
[Liberal DanuFed.zip](https://github.com/user-attachments/files/16104214/Liberal.DanuFed.zip)

**Comment by BestestIffers** [comment]
![Austria Bug Who](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/6ee9f57e-cae9-4d0d-9fe5-93059a9a6a06)
Also want to note, these foci should be bypassed since they're available in the initial tree

**Comment by BestestIffers** [comment]
![Austria Bug Yep](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/84541896/86b7b696-e527-4035-ae4b-295754440f89)
This decision boosts soclib popularity instead of the marlib's like it says

**Comment by MrCovenant000** [comment]
@BestestIffers not sure what the problem is on the last one. isnt it doing what it says it should

**Comment by MrCovenant000** [comment]
All done
