### ISSUE TITLE
Two Spains in accord voting

### ISSUE THREAD

**Issue by Funnymenindenmark** [kalterkrieg/Kalterkrieg-bug-reports#85]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

None

### Were you using Steam?

yes

### Were you in multiplayer?

no

### Explanation of the Issue

There seems to have been two spains appear on the accord voting menu

### Steps to reproduce

wait for spain or any other nation to join the accord (i believe) 

### Possible Cause

i believe it may be some sort of visual error that happens when Spain or another nation joins the accord however i am not fully sure

### Screenshots

![Screenshot 2024-07-05 171831](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/174779090/9d2a158a-2806-4d1e-814e-10e8571a5d9d)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
we were manually adding SPR to the array when already handled by alignment further up
