### ISSUE TITLE
Every Country - Troops Teleport When MAF Retreats From Madagascar

### ISSUE THREAD

**Issue by ForTheImperium** [kalterkrieg/Kalterkrieg-bug-reports#87]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

KR model and music submods

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

BBA, AAT, ToA

### Explanation of the Issue

All divisions of every country magically teleport when the news of MAF retreating from Madagascar appear.

### Steps to reproduce

Just wait till the news appear. It has also happened during my MAF Hippel run.

### Possible Cause

No idea.

### Screenshots

<img width="1280" alt="Eastern Front Pre-Teleportation" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/3ccf91fa-d4aa-4dad-8b05-ded84a5b62bb">
<img width="1280" alt="News and Teleportation" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/8b212276-e8c0-40b7-bde9-3fdd6f44aa16">
<img width="1280" alt="Eastern Front Post-Teleportation" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/0751ab12-e57a-427a-bfb1-3f9125ea2e66">
<img width="1280" alt="Chinese Civil War Post-Teleportation" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/b7afcdf8-96db-46ce-b911-85ac44655dc1">
<img width="1280" alt="French Soldiers Stuck in Desert" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/5ce197fa-f7b2-48b7-a9d8-2e0d6254e325">

### Save File

[RUS_1950_01_03_01.zip](https://github.com/user-attachments/files/16107735/RUS_1950_01_03_01.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16107744/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
Put out a hotfix to deal with this, so it is already fixed. Confirmed through logs that this game was not being played with this hotfix.
