### ISSUE TITLE
game freezing/locking up 

### ISSUE THREAD

**Issue by weakestbritishmodder** [kalterkrieg/Kalterkrieg-bug-reports#88]
### OS

Windows 10 Home

### HOI4 Version

1.14.7

### Kalterkrieg Version

Kalterkrieg 0.1

### List any other mods used

universal colored puppets   gamerule-based player peace   state transfer tool

### Were you using Steam?

yeah

### Were you in multiplayer?

no

### Which expansions do you NOT have?

have all of them but arms against tyranny was turned off

### Explanation of the Issue

The game started randomly freezing for several seconds and the longer I played the more often it happened and I reached 1954 and the game freezing was constant and made the game unplayable.

### Save File

[DNF_1954_01_28_01 wwwwwws.zip](https://github.com/user-attachments/files/16108374/DNF_1954_01_28_01.wwwwwws.zip)

### Log Files

[error.log](https://github.com/user-attachments/files/16108408/error.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by MrCovenant000** [comment]
Stt and play peace could be causing this so I am going to close this as we aren't yet making it compatible with these
