### ISSUE TITLE
Every Country - Troops Teleport When MAF Dissolves

### ISSUE THREAD

**Issue by ForTheImperium** [kalterkrieg/Kalterkrieg-bug-reports#90]
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

KR model and music submods

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

BBA, AAT, ToA

### Explanation of the Issue

Like the teleportation that happens when MAF retreats from Madagascar, all divisions of every country magically teleport when MAF dissolves.

### Steps to reproduce

Just wait.

### Possible Cause

Something about loading a new order of battle I guess

### Screenshots

<img width="1280" alt="Eastern Front Pre-Teleportation 2" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/ae7b920a-b676-450e-8a00-61db62a43b96">
<img width="1280" alt="Eastern Front Post-Teleportation 2 png" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/a27d9e09-1961-4311-9fcc-c1cb50e30e09">
<img width="1280" alt="Chinese Civil War Post-Teleportation 2" src="https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/103798469/47282024-ae4c-4872-a6ae-2d3d68dd87c5">

### Save File

[RUS_1950_12_24_11.zip](https://github.com/user-attachments/files/16109006/RUS_1950_12_24_11.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16109021/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Axolotl3823** [comment]
know issue has been solved for next hotfix
