### ISSUE TITLE
FRA - Algeria War quick victory results in White peace, Algerian favour

### ISSUE THREAD

**Issue by the-gemperor** [kalterkrieg/Kalterkrieg-bug-reports#91]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7.f4d3 (aa00) (s)

### Kalterkrieg Version

0.1

### List any other mods used

Toolpack without errors, Precise Buffs - Cheat Ideas. (Both Mods weren't appearing when playing game.

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

None

### Explanation of the Issue

Playing as Canada in 1954, and suddenly Algerian War kicks off. France sends in divisions, and takes all but one tile. Suddenly, there is a white peace, and Algeria regains everything.

### Steps to reproduce

- Let France kick off Algerian War in April 1954.
- Let them fight it out
- Have France destroy Algeria, but leave only one tile left

### Possible Cause

Not sure if France sent more than maximum divisions to Algeria, but other countries sent in divisions, though they were not at war. Also when reloading an earlier save and having the war play out again, France actually won, though there was a naval invasion that failed. That may have succeeded in the first round, and may have caused the French Divisions to go over the limit.

### Save File

[KRG Can 1.zip](https://github.com/user-attachments/files/16109090/KRG.Can.1.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment]
Fixed.
