### ISSUE TITLE
Canada - Unclear Text making decision difficult to judge

### ISSUE THREAD

**Issue by DapperT** [kalterkrieg/Kalterkrieg-bug-reports#92]
**Quick questions**
HOI4 version:
Kalterkrieg version:
List any other mods used:

**Explanation of the issue:**
The text in this event is very unclear and seemingly contradictory to what seems to be stated. I cannot tell if following the advice means the Government has freedom of action or not because of how it is written. Maybe it is just me, but I feel that this might need to be looked at to be less confusing. The body of text seems illogical, seemingly suggesting the government can act freely despite the addition of a check on power, not helped by the options further confusing the implications of each choice

**Screenshots:**
![image_2024-07-05_203815136](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/92275017/36882853-c5a6-40ec-98ca-610683f3b87d)

**Comment by Flizzyclone** [comment]
LOL this is like every logical error we could have made here. Will fix
