### ISSUE TITLE
NEWS - The Return of Alexander II, minor spelling mistakes

### ISSUE THREAD

**Issue by aggebojkalos** [kalterkrieg/Kalterkrieg-bug-reports#93]
**Quick questions**
HOI4 version:
1.14.7

Kalterkrieg version:
0.1

List any other mods used:
None

**Explanation of the issue:**
Highlighted in linked picture, "Govenor" I think should be "Governor", maybe add a comma after "However" so it doesn't look like "However Alexander" is his full name.

**Screenshots:**
![bild](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/130373997/6eb3c3c4-196b-47ca-b24f-211e512b3741)

**Comment by Kennedy2523** [comment]
Hey, thank you for your many many reports! They are very thorough and greatly appreciated. We need someone with that kind of attention to detail and dedication on the team. Please reach out to me on discord and we can chat about your becoming a tester. Cheers!
