### ISSUE TITLE
DNF - Chamber of Deputies Seats bug

### ISSUE THREAD

**Issue by Ramtendo** [kalterkrieg/Kalterkrieg-bug-reports#97]
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

Trial of Allegiance

### Explanation of the Issue

After I got the Liberals in Power in the Federal-Election, I broke up with the Balaton Bloc and formed a coalition with the SocDems, but the seats of the Chamber of Deputies is bugged.

### Steps to reproduce

Get the Liberals in Power at the federal-election, break up with the Balaton Bloc and form a coalition with the SocDems

### Screenshots

![Bild_2024-07-05_142610449](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/69436375/5ddd42a2-406e-4126-8b7f-6508b4a24b05)

### Save File

[DNF_1952_01_20_09.zip](https://github.com/user-attachments/files/16109690/DNF_1952_01_20_09.zip)

### Log Files

[error.log](https://github.com/user-attachments/files/16109697/error.log)
[game.log](https://github.com/user-attachments/files/16109701/game.log)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by MrCovenant000** [comment]
I have fixed this and it will be in a patch in coming days
